### ISSUE TITLE
GeoNode documentation for docker-compose out of date

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#1139]
Documentation [here](https://docs.geonode.org/en/master/install/advanced/core/index.html#override-the-env-variables-to-deploy-on-a-public-ip-or-domain) seems to be outdated

Among other things it's referencing 3.2 and advising to use a docker-compose override instead of .env file

**Comment by giohappy** [comment]
moved to https://github.com/GeoNode/documentation/issues/236
