### ISSUE TITLE
Test Geonode 3.3.x for release

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1140]
@ElenaGallo we need to run the full test suite on development demo (3.3.x), to prepare the release of version 3.3.1.

**Comment by giohappy** [comment]
@ElenaGallo please add a test for the correct initialization of the timeline histogram for vector time series (see https://github.com/GeoNode/geonode-mapstore-client/issues/756 and https://github.com/GeoNode/geonode-mapstore-client/issues/757)

**Comment by giohappy** [comment]
@Stella-Nthenya can you please review the failed tests from @ElenaGallo?
I invite you to replicate them and open any issue. Please attach the issues to this epic.

**Comment by Stella-Nthenya** [comment]
The following testcases are working; 
1. This [Testcase](https://studio.cucumber.io/l/ts/30817638) has passed, see drive link [demo](https://drive.google.com/file/d/1QxCN0AC6q8avaVyjxphdmQXAJzRXoVEo/view?usp=sharing)
2. This [Testcase](https://studio.cucumber.io/l/ts/30817727) has passed, see drive link [demo](https://drive.google.com/file/d/1UVmRD02ntdJJV5AKpD8__22BSghlZgXP/view?usp=sharing)
3. This [Testcase](https://studio.cucumber.io/l/ts/30817674) has passed, see drive link [demo](https://drive.google.com/file/d/1q3yGhH1X8obQMkfGopGoR4Xg8EAJG7Py/view?usp=sharing)

**Comment by Stella-Nthenya** [comment]
> The following testcases are working;
> 
> 1. Set thumbnail from Medatada wizard: This [Testcase](https://studio.cucumber.io/l/ts/30817638) has passed, see drive link [demo](https://drive.google.com/file/d/1QxCN0AC6q8avaVyjxphdmQXAJzRXoVEo/view?usp=sharing)
> 2. Print maps: This [Testcase](https://studio.cucumber.io/l/ts/30817727) has passed, see drive link [demo](https://drive.google.com/file/d/1UVmRD02ntdJJV5AKpD8__22BSghlZgXP/view?usp=sharing)
> 3. Set map thumbnail from Medatada wizard: This [Testcase](https://studio.cucumber.io/l/ts/30817674) has passed, see drive link [demo](https://drive.google.com/file/d/1q3yGhH1X8obQMkfGopGoR4Xg8EAJG7Py/view?usp=sharing)

**Comment by ElenaGallo** [comment]
> The following testcases are working;
> 
> 1. This [Testcase](https://studio.cucumber.io/l/ts/30817638) has passed, see drive link [demo](https://drive.google.com/file/d/1QxCN0AC6q8avaVyjxphdmQXAJzRXoVEo/view?usp=sharing)
> 2. This [Testcase](https://studio.cucumber.io/l/ts/30817727) has passed, see drive link [demo](https://drive.google.com/file/d/1UVmRD02ntdJJV5AKpD8__22BSghlZgXP/view?usp=sharing)
> 3. This [Testcase](https://studio.cucumber.io/l/ts/30817674) has passed, see drive link [demo](https://drive.google.com/file/d/1q3yGhH1X8obQMkfGopGoR4Xg8EAJG7Py/view?usp=sharing)

@giohappy @Stella-Nthenya now the three cases above work for me too.

**Comment by giohappy** [comment]
@Stella-Nthenya are all the tests working now? If not please open the issues.
