### ISSUE TITLE
Test Geonode 3.2.x for release

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1148]
@ElenaGallo we need to run the full test suite on development demo (3.2.x), to prepare the release of version 3.2.3.

Add a test as reported in this comment https://github.com/geosolutions-it/geonode/issues/1140#issuecomment-1025510817

**Comment by giohappy** [comment]
@Stella-Nthenya can you please review the failed tests from @ElenaGallo?
I invite you to replicate them and open any issue. Please attach the issues to this epic.

**Comment by ElenaGallo** [comment]
@giohappy I tested the stable demo, [here](https://studio.cucumber.io/projects/192843/test-runs/633696/folder-snapshots/6470609) the result of the test run 3.2.x.

I only found  [this problem](https://studio.cucumber.io/projects/192843/test-runs/633696/folder-snapshots/6470646/scenario-snapshots/22646757/test-snapshots/31113627) also found on 3.3.x and another problem is that many layer thumbnails, maps, images, videos are broken.
