### ISSUE TITLE
Prepare a proposal to improve the communication between devs and testers

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1149]
Until now there wasn't a structured way to align news and changes to GeoNode features to the manual tests (BDD on Cucumber Studio now). An informal communication was done when a new test had to be run before a release (GeoNode release or customer specific project). This approach is falling short now for several reasons:

 - we want to test changes and news as soon as they get merged (and deployed to demo), without waiting for a full run in the future
 - we don't want to incur a risk of having cricital features not covered by manual tests
 - we have branches with different feature sets, so it's becoming difficult to keep track of the differences

We need to agree on a procedure to make the test team aware of any change that affects the UI/UX and the expected results of any operation performed through by a user. The test team must be placed in a position to verify and test the change, and give feedback promptly.

The first step is **do not automatically close an issue when it's merged**. The issue **must be moved to the "In Test"** column inside the Zenhub board. 
However, an appropriate description of the changes and the expected results (Acceptance criteria) must be formulated inside the issue so that testers have all the information to test the functionality when it lands into the In Test column.

@Stella-Nthenya the above points are just my personal notes but I would like you to submit a proposal, given your experience on the topic, that shall be discussed with the devs team once it's ready.

**Comment by giohappy** [comment]
@Stella-Nthenya we migh even include some GitHub automation (actions / workflows) to support the tracking of issues that need a review + testing from testers. I'll let you think about it, but a mix of actions based on pushes and ad-hoc labels could, for example, create automatic comments to invite testers to review the issue, send notifications, block the autoclose of an issue, whatever...

**Comment by Stella-Nthenya** [comment]
Sure @giohappy, some automation is needed. Let me review my document and send you my proposal with that in addition.

**Comment by giohappy** [comment]
@marthamareal I invite you to read what [Stella wrote](https://drive.google.com/file/d/1r1z1REsShlXAKXFNBTxKSoMx_ZUebuR-/view?usp=sharing), inc ase there's something useful
