### ISSUE TITLE
Missing resource type for some uploaded datasets

### ISSUE THREAD

**Issue by Stella-Nthenya** [geosolutions-it/geonode#1150]
### Steps to reproduce

1. Upload [this dataset](https://app.zenhub.com/files/23841932/f4c5d9e7-c27b-48c6-9d5d-9ad8eea3fa44/download)
2. Verify that it has been assigned the correct resource type

### Expected Behaviour
The `dataset` resource type is assigned.

### Actual Behaviour
resource type is missing.

**Comment by giohappy** [comment]
@marthamareal apparently this happens becuase of the additional files contained inside the sample dataset. If only the 4 files for the shapefile are uploaded the resource_type is correctly assigned.

Also notice that the dataset is correctly imorted in Geoserver, and the thumbnail is created. 
I suspect that an exception occurs during the processing of the additional files and the resource_type assignment is skipped.

**Comment by giohappy** [comment]
closing in favour fo https://github.com/geonode/geonode/issues/8721
