### ISSUE TITLE
Annotations added to a map are not saved

### ISSUE THREAD

**Issue by Stella-Nthenya** [geosolutions-it/geonode#1152]
## Expected Behavior
Annotations added to a map should be viewable from on the map area when a user;

- navigates back to the map at any time 
- refreshes the map page after saving the added annotations

## Actual Behavior
Annotations are not viewable after creation + saving.

## Steps to Reproduce the Problem

  1. Create an annotation
  2. Make any necessary edits and styling
  3. Click on save
  4. Refresh the page
  5. Navigate to the homepage and back again to the subject map
  6. Confirm that the added annotations are viewable

## Specifications

  - GeoNode version: 3.3x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: Web
  - Additional details:
[DRIVE LINK VIDEO](https://drive.google.com/file/d/1xEzn3unxw3Fj4se6pS7nL4WXV28AwYUL/view?usp=sharing)

**Comment by Stella-Nthenya** [comment]
@giohappy kindly help review and assign this issue

**Comment by Stella-Nthenya** [comment]
This affects printing of maps with annotations too,

**Comment by giohappy** [comment]
@Stella-Nthenya please open the issues on the upstream repo, and connect them to the test epic.
See how I did it for this one, which I'm closing in favour of https://github.com/GeoNode/geonode/issues/8743
