### ISSUE TITLE
Setup 2.20.x build for GeoNode

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1215]
Upstream issue https://github.com/GeoNode/geonode/issues/8981

I'm opening this as an internal issue to discuss the configuration of our Jenkins builds.

**Comment by randomorder** [comment]
existing build for the older version @lpasquali 
http://build.geo-solutions.it/jenkins/job/GeoNode-GeoServer-EXT-2.19.x/

please document all the process. We'll review and try to automate it

**Comment by lpasquali** [comment]
@randomorder is this document good for the scope? https://docs.google.com/document/d/1OoByab707l3HGGIbq4aCKeiw5LUlZ8rCUmv6axSeiP4/edit#heading=h.gjdgxs

**Comment by randomorder** [comment]
indeed. Very good

**Comment by randomorder** [comment]
There's  catch @giohappy 
Branches are named after nightly versions
![image](https://user-images.githubusercontent.com/5264230/163377786-400ad2c7-c59c-4f13-86f9-de130b620695.png)

but the POMs are pointing to stable versions of GeoServer
https://github.com/GeoNode/geoserver-geonode-ext/blob/2.19.x/geoserver/pom.xml#L83

I would like to fix this from now one. Please confirm it's of with you to point to geoserver `2.20.4` and Not 2.20.x nightly

**Comment by randomorder** [comment]
@lpasquali please create a sepate issue with an estimate for the migration of the jobs to the new build server

**Comment by randomorder** [comment]
reopen if needed @giohappy
