### ISSUE TITLE
UNMISS WMTS service to be used as basemap 

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/geonode#1216]
We've received from UN 3 remote service, ArcGIS based, to be consumed as basemaps within GeoNode UNMISS platform.
GeoNode version is 3.2.4

After some tests, we found out that those services are not working on UN GeoNode while they're fine in QGIS.
Below the received errors:
1.
https://dev-ags1.dfs.un.org/arcgis/rest/services/UNMISS_Custom_Basemap/MapServer
GeoNode ArcGIS Rest Service : We were able to connect to services, we've received the resource but we’ve got Timeout error when trying to harvest some layers
2.
https://dev-ags1.dfs.un.org/arcgis/rest/services/UNMISS_Custom_Basemap/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
GeoNode WMTS service: : We’ve got unknown URL address error
3.
https://dev-ags1.dfs.un.org/arcgis/services/UNMISS_Custom_Basemap/MapServer/WMSServer?request=GetCapabilities&service=WMS
GeoNode WMS service: We’ve got unknown URL address error

Services are only working within UN intranet.
To connect with UN intranet:
https://docs.google.com/document/d/1S4ZaOFhIEgS-cupQO7IoR-W6AO0Q0ZcE/edit

We've asked to have the services publicly available, they said they'll provide them in the next days.

**Comment by giohappy** [comment]
@EddyCatt GeoNode version?

**Comment by giohappy** [comment]
@EddyCatt in breif:

 - WMS for basemaps is already supported. It requires a configuration inside `DEFAULT_MS2_BACKGROUNDS` [GeoNode settings](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1455).
 - WMTS basemaps require an [enhancement](https://github.com/GeoNode/geonode-mapstore-client/issues/280) that was already in the backlog
 - ArcGIS Mapserver... MapStore can show ArcGIS layers but I don't know if it exposes the settings to configure them as basemaps. @allyoucanmap can you enlighten us on this?

**Comment by EddyCatt** [comment]
Services are now publicly available
I've successfully added the WMS service 
[](https://pro-ags1.dfs.un.org/arcgis/services/UNMISS_Custom_Basemap_CVW/MapServer/WMSServer)
as remote service in 
[](https://development.demo.geonode.org/services/284/)

![image](https://user-images.githubusercontent.com/86973955/166501375-5bf447d6-b00a-4c7b-badc-84a3476478a1.png)

**Comment by EddyCatt** [comment]
Services are now publicly available
UNMIss would like to use the following WMS services as basemap for GeoNode 
(https://pro-ags1.dfs.un.org/arcgis/services/UNMISS_Custom_Basemap_CVW/MapServer/WMSServer)

I'd need support to configure it as basemap DEFAULT_MS2_BACKGROUNDS [GeoNode settings](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1455).

**Comment by mattiagiupponi** [comment]
@EddyCatt @giohappy 
Follows the config to be added under the GeoNode settings file:

```python
{
    "type": "wms",
    "title": "UNMISS WMS",
    "format": "image/jpeg",
    "id": "unimiss",
    "name": "unimiss:unimiss",
    "url": "https://pro-ags1.dfs.un.org/arcgis/services/UNMISS_Custom_Basemap_CVW/MapServer/WMSServer",
    "thumbURL": "https://unmiss.unmissions.org/sites/all/themes/unmpk/logo.png",
    "group": "background",
    "visibility": False
},
```

if is needed as a default background, is needed to:
- in the configuration change the "Open Street Map" -> visibility from `TRUE` to `FALSE`
- change the above configuration for unimiss -> visibility from `FALSE` to `TRUE`

The only issue that I see now is that the background looks empty for every resource:

![image](https://user-images.githubusercontent.com/51856725/166703685-68c95ada-c9b9-447c-a544-629e4a8960ab.png)

**Comment by mattiagiupponi** [comment]
@EddyCatt we were able to load a background with ID 3:
config
```python
{
    "type": "wms",
    "title": "UNMISS LND_Landcover_S",
    "format": "image/jpeg",
    "id": "3",
    "name": "3",
    "url": "https://pro-ags1.dfs.un.org/arcgis/services/UNMISS_Custom_Basemap_CVW/MapServer/WMSServer",
    "thumbURL": "https://unmiss.unmissions.org/sites/all/themes/unmpk/logo.png",
    "group": "background",
    "visibility": False
},
```

The output as a background is the following:
![image](https://user-images.githubusercontent.com/51856725/166716668-2f4861c5-5f03-482b-a57b-4278eb7d2ec4.png)

**Comment by giohappy** [comment]
@EddyCatt the tile layer configuration is:

```
{
    "type": "tileprovider",
    "title": "UNMISS Basemap",
    "provider": "custom",
    "name": "",
    "group": "background",
    "visibility": false,
    "url": "[https://pro-ags1.dfs.un.org/arcgis/rest/services/UNMISS_Custom_Basemap_CVW/MapServer/tile/{z}/{y}/{x}](https://pro-ags1.dfs.un.org/arcgis/rest/services/UNMISS_Custom_Basemap_CVW/MapServer/tile/%7Bz%7D/%7By%7D/%7Bx%7D)",
    "thumbURL": "https://unmiss.unmissions.org/sites/all/themes/unmpk/logo.png",
}
```

**Comment by EddyCatt** [comment]
UN Basemap configuration should be deployed in production environemnt
