### ISSUE TITLE
Build Geoserver 2.19.x for Geoserver with KMLPPIO plugin

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1224]
We need to ship Geoserver 2.19.x for GeoNode ((and 2.20.x [afterwards](https://github.com/geosolutions-it/geonode/issues/1215)) with the [KMLPPIO plugin](https://build.geoserver.org/geoserver/2.19.x/community-latest/geoserver-2.19-SNAPSHOT-kmlppio-plugin.zip).

A new [build of the Geoserver 2.19.x war](https://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.19.x/) is needed. 

I suppose we can keep the same s3 link @randomorder right? This way no change is required on the GeoNode side.

**Comment by randomorder** [comment]
Ok @giohappy the plugin is in the GeoServer 2.19.x already 
I had a go with @aaime on [stable geonode](https://stable.demo.geonode.org/maps/new?layer=geonode:Asansol&view=True#/)

![image](https://user-images.githubusercontent.com/5264230/160833816-d623c091-a6cf-4d37-9672-04aaadb5cfb5.png)

KML is not there so I have tweaked the outputformat from the CSV request
![image](https://user-images.githubusercontent.com/5264230/160833900-c28793b8-5bea-43b4-b4c8-1ca8c91ea103.png)

```
  <wps:Input>
     <ows:Identifier>outputFormat</ows:Identifier>
     <wps:Data>
        <wps:LiteralData>application/vnd.google-earth.kml+xml</wps:LiteralData>
     </wps:Data>
  </wps:Input>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
   <ows:Identifier>gs:Download</ows:Identifier>
   <wps:DataInputs>
      <wps:Input>
         <ows:Identifier>layerName</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>geonode:Asansol</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>outputFormat</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>application/vnd.google-earth.kml+xml</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>false</wps:LiteralData>
         </wps:Data>
      </wps:Input>
   </wps:DataInputs>
   <wps:ResponseForm>
      <wps:ResponseDocument storeExecuteResponse="true" status="true">
         <wps:Output asReference="true">
            <ows:Identifier>result</ows:Identifier>
         </wps:Output>
      </wps:ResponseDocument>
   </wps:ResponseForm>
</wps:Execute>
```
![image](https://user-images.githubusercontent.com/5264230/160834222-4c03c9f9-1a9d-4df6-a98d-da2f0f6f9cd0.png)

[result (1).zip](https://github.com/geosolutions-it/geonode/files/8380397/result.1.zip)


By the way, you probably know already but I report that GeoNode is using WFS for the download of the vector data and mapstore is using WPS instead:
This is from GeoNode: 

https://stable.demo.geonode.org/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typename=geonode%3AAsansol&outputFormat=SHAPE-ZIP&srs=EPSG%3A4326&format_options=charset%3AUTF-8

![image](https://user-images.githubusercontent.com/5264230/160834419-09afc6cc-e004-442f-947e-d1bcd98c3067.png)

When we create the branch for GS for GeoNode version 2.20.x the plugin will be there for free
