### ISSUE TITLE
Test Upgrading from 3.x to 4.x

### ISSUE THREAD

**Issue by marthamareal** [geosolutions-it/geonode#1225]
- Start a project on 3.x
- Create resources (layers, maps, documents,geoStories and dashboards)
- Upgrade to 4.x
- Test listing, updating and deleting resources created with 3.x

**Comment by marthamareal** [comment]
@giohappy The error 

`django.db.utils.IntegrityError: update or delete on table "geoapps_geoapp" violates foreign key constraint "geoapp_geostories_ge_geoapp_ptr_id_2a57fe28_fk_geoapps_g" on table "geoapp_geostories_geostory"
DETAIL:  Key (resourcebase_ptr_id)=(2) is still referenced from table "geoapp_geostories_geostory".`

resulting from upgrading project from 3.3.x  to 4.x when having resources(dashboard or geostory) is replicable.

**Comment by giohappy** [comment]
so this confirms the issue we saw yesterday. Open an issue and assign it to yourself.
