### ISSUE TITLE
Test GeoNode 4.x for release 4.0RC1

### ISSUE THREAD

**Issue by marthamareal** [geosolutions-it/geonode#1233]

**Comment by ElenaGallo** [comment]
Hi @marthamareal @giohappy, I have created a new [test run](https://studio.cucumber.io/projects/293168/test-runs/654108/overview). If there are no problems I proceed to run it.

**Comment by marthamareal** [comment]
@ElenaGallo i was also planning to add test-cases for `Harvesters`, @giohappy can you confirm that we need to also test this feature for this release.

**Comment by giohappy** [comment]
yes @marthamareal, testing for both harvesters and remote services is needed.

**Comment by marthamareal** [comment]
@ElenaGallo Before starting a test run, could you give me some time to add these new test cases and also some other cases which cover newly added features eg(upload size limit).

**Comment by ElenaGallo** [comment]
@marthamareal no problem, let me know when I can start.

**Comment by marthamareal** [comment]
@ElenaGallo I have added some test-cases and updated the mentioned test-run with them, you can proceed when you're ready

**Comment by ElenaGallo** [comment]
@marthamareal @giohappy Test run done. [Here](https://studio.cucumber.io/projects/293168/test-runs/654604/overview) the result.
