### ISSUE TITLE
Build Geoserver for GeoNode 2.18.x and 2.19.x to include the fix from GEOS-10437

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1241]
https://osgeo-org.atlassian.net/browse/GEOS-10437 has been backoported.
It fixes https://github.com/geosolutions-it/support/issues/1967

A new build of Geoserver for GeoNode 2.18.x and 2.19.x is required.

**Comment by randomorder** [comment]
new geoserver WAR files are out [https://artifacts.geonode.org/index.html](https://artifacts.geonode.org/index.html)

I am about to update Master, Stable and Development demos
