### ISSUE TITLE
Unable to upload dataset style

### ISSUE THREAD

**Issue by marthamareal** [geosolutions-it/geonode#1243]
## Expected Behavior
Users should be able to upload styles successfully

## Actual Behavior
- Style uploading does not complete, the GeoServer configuration step never ends.
-  multiple GET `upload/progress`  requests return `state: "NONE"`
![ss](https://user-images.githubusercontent.com/20810749/163224857-e72eef85-b700-4216-9b6e-93154c27a3f9.png)

## Steps to Reproduce the Problem

  1. Go to https://master.demo.geonode.org
  2. Select a dataset and click on Edit > Upload Style
  3. Notice the process never ends

## Specifications 

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@giohappy @afabiani i think this issue relates with this https://github.com/GeoNode/geonode/issues/9096

**Comment by afabiani** [comment]
@marthamareal yes, that PR fixes this one too
