### ISSUE TITLE
create stable branches for geoserver-geonode-ext

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#1246]
- [x] 2.18.6
- [x] 2.19.6
- [x] 2.20.4

**Comment by giohappy** [comment]
Geoserver 2.19.6 -> https://github.com/GeoNode/geoserver-geonode-ext/tree/2.19.6
Geoserver 2.18.6 -> https://github.com/GeoNode/geoserver-geonode-ext/tree/2.18.6
Geoserver 2.20.4-> https://github.com/GeoNode/geoserver-geonode-ext/tree/2.20.4
