### ISSUE TITLE
update docker images for geoserver-geonode-ext

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#1249]

**Comment by lpasquali** [comment]
Pull request for master geonode-project: https://github.com/GeoNode/geonode-project/pull/284

**Comment by lpasquali** [comment]
Published all datadir docker images:

geonode/geoserver_data:2.18.6
geonode/geoserver_data:2.19.6
geonode/geoserver_data:2.20.4

updated related branches

**Comment by lpasquali** [comment]
Pull request for 4.x (GeoServer 2.20.4) here: https://github.com/GeoNode/geonode-project/pull/287

**Comment by lpasquali** [comment]
Pull requesty for 3.3.x (GeoServer 2.19.6) here: https://github.com/GeoNode/geonode-project/pull/286

**Comment by lpasquali** [comment]
made PR for geonode/geonode
![Screenshot from 2022-04-15 19-22-36](https://user-images.githubusercontent.com/1780406/163601450-3d98cbdd-f632-4abc-a10e-648a67b13905.png)

**Comment by randomorder** [comment]
PRs are out @giohappy

**Comment by randomorder** [comment]
please pu a link to the updated docuentation for the creation of the docker images

**Comment by lpasquali** [comment]
@randomorder 

 https://docs.google.com/document/d/1OoByab707l3HGGIbq4aCKeiw5LUlZ8rCUmv6axSeiP4/edit#

**Comment by randomorder** [comment]
that's the documentation I wrote based on the build process against geonode-project.
But you said you are building from https://github.com/GeoNode/geoserver-docker , right?

**Comment by lpasquali** [comment]
@randomorder I referred the same document as we need the same place as geoserver-docker it is fundamental for geonode-project, because its circleci pipeline is depending on docker images for geoserver

**Comment by randomorder** [comment]
@set-reminder tomorrow 12:50

**Comment by lpasquali** [comment]
@randomorder as required by @giohappy I updated PR for 4.x to 2.19.6, it is here:

**Comment by lpasquali** [comment]
@giohappy @randomorder all remaining PR have been made for geonode-project and geonode
all docker images have been uploaded and related branches pushed to github
there should be nothing left as of now

**Comment by lpasquali** [comment]
@randomorder linked doc above has been updated with all images, repositories involved on a geoserver update

**Comment by randomorder** [comment]
waiting for feedback from @giohappy

**Comment by giohappy** [comment]
From what I see we're doing, right?

**Comment by randomorder** [comment]
we're just waiting for feedback on the testing before closing the issue

**Comment by giohappy** [comment]
@randomorder I've just updated Geoserver for stable demo (3.2.x) and it also look good.

**Comment by randomorder** [comment]
thanks @giohappy
