### ISSUE TITLE
Test GeoNode 3.3.x for 3.3.2 release

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#1300]
Please @ElenaGallo chat with @marthamareal to review the latest version of the Cucumber suite for 3.3.x before running the tests.

**Comment by ElenaGallo** [comment]
Hi @giohappy @marthamareal, all tests passed except these two about the print in the MS viewer.

[Test on Cucumber](https://studio.cucumber.io/projects/291214/test-runs/666426/folder-snapshots/6856125)


![print](https://user-images.githubusercontent.com/56537133/169863119-67e01d7b-08ea-4138-93ae-997fc68befd6.gif)

**Comment by giohappy** [comment]
ok,. it's a misconfiguration. The [print info](https://development.demo.geonode.org/geoserver/pdf/info.json) reports the local URL instead of the public URL.
We will check if it's a problem that only affects the demo server.
