### ISSUE TITLE
[Disasterrisk] Squash migrations and regenerate initial fixtures with correct data

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#140]

**Comment by cezio** [comment]
missing items:
 * [ ] cost benefit hazards, analysis types, icons for at
 * [ ] cost benefit report
 * [ ] cost benefit dimensions (other than scenario, round periods): Focus Area Analysis
 * [ ] improved geometries (more precise?)

**Comment by cezio** [comment]
I've created squashed migration, but it's not valid, since we use callables in few cases to populate data:

```
  File "/mnt/work/cezio/geosolutions/repos/geonode/geonode/contrib/risks/migrations/0001_squashed_0046_riskanalysisdymensioninfoassociation_layer_reference_attribute.py", line 484
    field=models.ForeignKey(default=geonode.contrib.risks.migrations.0037_risk_analysis_app.get_default_app, to='risks.RiskApp'),
                                                                        ^
SyntaxError: invalid syntax
```

**Comment by cezio** [comment]
I've updated migrations, moved callables to risks.models. generated squashed migration file should not complain about invalid syntax no more.
