### ISSUE TITLE
[Disasterrisk] PDF Reports: general improvements to the template

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#162]
- [x] Add complete cover page with disclaimers and references

 - [x] Display the Abstract of the Risk Analysis instead of the DB name

 - [x] The report must print also the current selected Dimensions along with their UoMs

 - [x] For Cost Benefit Analysis the report should also print the additional charts

 - [x] Display also icons where possible (e.g. Category, Hazard, and so on...)

 - [x] Avoid displaying fields like "fa-icon"

**Comment by cgiovando** [comment]
Minor aesthetic issue: when hovering with the mouse pointer on the top menu, the highlighted boxes don't line up with the banner height.... see below

![apr-13-2017 16-59-32](https://cloud.githubusercontent.com/assets/10201533/25028628/a57e88f8-206a-11e7-8410-bd4740245223.gif)
