### ISSUE TITLE
[UNESCO IHP-WINS] Allow UNESCO-IHP's admins to make a final check on every data uploaded before it goes visible by everyone.

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode#175]
This is to prevent public sharing of incorrect data or metadata incorrectly filled.
Every time new data is uploaded, admins must be notified to be able to check it. Until that verification is done, data remains visible only by its owner and IHP's admins. Once it is checked, IHP's admins change data permissions to make it visible according to its owner's will.

**Comment by cezio** [comment]
my idea here:
* there should be additional setting, ``ADMIN_MODERATE_UPLOADS`` or something like that (boolean flag), which would enable this feature (i guess other deployments in use expect uploads to work in the way they do now, so we shouldn't break that behavior)
* 
* what should we do with permissions settings in upload view?

**Comment by cezio** [comment]
my idea here:

* this changes upload behavior. I guess current users would like to stay with current behavior, so I'll add switch in settings, ``ADMIN_MODERATE_UPLOADS`` (or something like that)
* because this affects layers, documents and maps, I'll add ``ResourceBase.created_notification()``, which will be called in upload views. I believe we want to avoid notifications when resource is created from script (backup restore, geoserver sync etc).
* currently user can specify permissions during upload. I'm not sure what to do with it. I see few options:
 * hide permissions ui if feature is on
 * ignore permissions
 * leave it as it is, admin can change that
* about permissions, I don't see any ui in admin. can we point admin to regular resource view to edit permissions?

**Comment by afabiani** [comment]
Your proposal is ok, please proceed ad you specified.

About permissions, I would leave them as they are (if possible) and hide the "unpublished" resource to users not belonging to Admin group (staff members) and the Owner of the resource.

If not possible, I would force the permissions and hide the form when uploading.

It would be great if there is also the possibility from the admin dashboard to choose which "Groups" or "Users" may edit "unpublished" resources, or at least enable an "Editor" checkbox (similar to "Staff") allowing them to view unpublished resources.

*WARNING* It must be very clear from the UI which are "Draft" resources. Maybe a different color or a red asterisk.

**Comment by cezio** [comment]
> (if possible) and hide the "unpublished" resource to users not belonging to Admin group (staff members) and the Owner of the resource.

The quickest way would be to set it as unpublished. Permissions would be preserved as selected by user. 

i've noticed this setting: http://docs.geonode.org/en/master/reference/developers/settings.html#resource-publishing
it seems to be used with documents only, sets published flag to False if enabled. I'm not sure if I can reuse it and extend it's usage. It works in similar way, but it's not yet applied to layers or maps.

**Comment by cezio** [comment]
there's additional app, https://github.com/GeoNode/geonode-notification which **probably** could be used for notifications. I'll check if will it work here

**Comment by cezio** [comment]
Geonode-notification app is out-of-date. It's based on old version of pinax app, which has been updated since last commit there. It has some template inheritance problems (settings template inherits from geonode-user-account, another pinax app fork, which inherits from ``account/base.html``, which is not present in any app). Another problem is integration code in GeoNode, which also doesn't work. GeoNode uses ``post_migrate`` signal to create notification types after notification app is migrated. But it uses old signal signature, and passes model module as a sender, instead of ``AppConfig`` instance, so this code:
https://github.com/GeoNode/geonode/blob/5bd1bfa794d92bb47b2e113f22a1fe1ed1257ff4/geonode/layers/management/__init__.py#L55
won't work. 

From chat with Alessio: GeoNode notifications are under big rewrite in master branch (new GN version will require AMQP broker running: https://github.com/GeoNode/geonode/issues/2889), making current notifications  infra obsolete.

I'll add code that will mark affected resource types as unpublished, when created from upload. Admin will be able to switch objects on in edit view. Permissions will be preserved. I guess notifications part will be handled independently with new infrastructure.

**Comment by cezio** [comment]
At the moment, my plan (partially implemented) is:
 * when moderation flag is on, uploads will have ``is_published`` flag set to ``False`` by default.
 * notifications will be handled with notifications app (``pinax-notifications``), so there would be no code duplication. Notifications handle resource changes, and are configurable. 

I see a place for small improvements here. Currently notifications are send after each change. We could add separate notification types for moderation only, which will be send only if change is from different user, and only from view (so no flood of notifications when data are updated from scripts).

**Comment by cezio** [comment]
Main difference between geonode-user-account and upstream's django-user-account is account registration moderation and invitations. i'm not sure if new version of pinax app can do invitations. We can move this functionality to separate app. Registration moderation can be implemented in geonode core, work optionally only if account app is installed (similar to notifications), and be hooked with signals. 

My idea here is to:
  * use pinax django-user-account app,
  * move invitations to geonode-account app (and thin it a lot from rest of the code)
  * move registration moderation to signal handler

There's also one more aspect to remember: data migration between apps. i can write simple script that would copy table contents from old apps to new ones

**Comment by cezio** [comment]
> move invitations to geonode-account app (and thin it a lot from rest of the code)
> move registration moderation to signal handler

This changed a bit:
 * registration moderation and invitations features were ported to upstream:
 (https://github.com/pinax/django-user-accounts/pull/254 and https://github.com/pinax/django-user-accounts/pull/256). 
 * sending notifications after user is registered when moderation flag is set is implemented in geonode core:

**Comment by cezio** [comment]
This is implemented:
* when ``ADMIN_MODERATE_UPLOADS`` flag is set, all uploads will be unpublished by default
* notifications will be handled by ``pinax-notifications`` app.

Waiting for https://github.com/GeoNode/geonode/pull/3047 to be merged into geonode
