### ISSUE TITLE
[UNESCO IHP-WINS] Automatically generate username from first/last names

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode#185]
When a person registers to create an account, automatically generates the user name based on the first name and last name (username must have this format: Firstname.Lastname). This user name must not be modified by the user.

**Comment by cezio** [comment]
This requires changing signup form to require first/last name instead of username. More details are here: http://django-user-accounts.readthedocs.io/en/latest/usage.html#customizing-the-sign-up-process

**Comment by cezio** [comment]
Few questions:

 * should we allow to modify first/last names in profile view?
 * if yes, what if first/last name change, should username be recreated?
 * what if we're missing first/last names? I'd assume they are required, but user can be created in different ways (manually by admin in admin view, with django command etc). 
 * what about invitations? they require email only, so username can't be generated in that moment. Should we advise disabling invitations here?

**Comment by afabiani** [comment]
Hi @cezio 

- Yes, first/last name should still be editable on profile
- Nope, username remains the same. At most we can allow to change it manually
- If one of First/Last name is missing, username must be inserted manually
- Email should become mandatory. We can still allow people to insert a custom username. That option of automatic generation should be optional imho, and enabled only when someone register itself from GeoNode interface

Last consideration, the automatic generation of username, should also check for duplicates. If that username is not available, then we can add a progressive number ad the end.

**Comment by cezio** [comment]
> Email should become mandatory. We can still allow people to insert a custom username. That option of automatic generation should be optional imho, and enabled only when someone register itself from GeoNode interface

I'm not sure if we could differentiate forms depending if it's invitation or direct registration. I'd prefer to keep this simple and require first/last name during registration only (no username).
