### ISSUE TITLE
[monitoring] calculate metrics for WxS services 

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode#190]
At the moment, we don't identify WxS, but we should. it should be separate resource type (although we won't be able to correlate layer with WxS then).

**Comment by cezio** [comment]
WxS service is kept in ``Metric.ows_service``. Client can filter by OWS service name by using ``ows_service=<OWS_NAME>`` query param in ``/monitoring/api/metric_data/<METRIC_NAME>/`` endpoint.

Additionally, list of all OWS services handled is available under ``/monitoring/api/ows_services/``.

**Comment by cezio** [comment]
This is acutally a bit faulty, because i've made an assumption that resource will have only one ows service linked, but vector layers can be returned as WFS and rendered into raster tiles as well, so this needs to be included in calculations.

**Comment by mekanix** [comment]
As frontend needs to display "W*S data", services need to be aggregated.

**Comment by cezio** [comment]
this should work now: ``/monitoring/api/metric_data/request.count/?valid_from=2017-06-01&ows_service=all```
