### ISSUE TITLE
[monitoring] notifications integration

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode#193]
Things to do:
 * [x] mechanism for running checks on metrics
 * [x] mechanism for configuring metrics to check (with thresholds)
 * [x] api for status to get list of notifications checks
 * [x] composing multiple alerts into one message in one run 
 * [x] sending messages with notifications app
 * [x] sending messages to non-registered users (emails only)

**Comment by cezio** [comment]
Implementation notes:
There are three main model classes:

``NotificationCheck`` is a high-level alert description and configuration holder. It keeps a list of metric-specific definitions in ``NotificationMetricDefinition``. 

Each ``NotificationMetricDefinition`` keeps per-metric user thresholds (min, max values for metric check) and flags indicating if user can limit scope to specific resource/service/label/ows service (this is not yet implemented fully).

Based on ``NotificationMetricDefinition``, form is generated to validate user's configuration, and then per-user configuration is created in ``NotificationCheck.process_user_form()``. From form data, new ``MetricNotificationCheck`` objects are created. Those are per-user-per-metric check configurations, so an user can have customized alert (for example: tight check for remote admin and some light checks for local operator).

**Comment by cezio** [comment]
Documentation: https://github.com/geosolutions-it/geonode/wiki/Monitoring:-Notifications

**Comment by cezio** [comment]
For frontend we need:
 * [ ] status api view
 * [ ] list of notifications
 * [ ] existing notification configuration

**Comment by cezio** [comment]
From chat with @mekanix: for status api, i'll remove check key (it's not needed, and it should be a list acutally), add url to notification check to each item in `problems`, and add `health_level` key with highest `severity` reported in `problems.

**Comment by cezio** [comment]
also, few other changes:
 * [ ] add `active` flag to notification
 * [ ] add `min`/`max`/`steps` values to check fields
 * [ ] add `current_value` to check field

**Comment by cezio** [comment]
more from call with Goran/Simone:
 * [ ] add metric check's and notification's description to errors reported in status api.

**Comment by mekanix** [comment]
Frontend needs info if config has only on/off switch or it has a value and the unit.

**Comment by cezio** [comment]
#247 related.

Few explanations, how frontend should construct such form:

 * Backend supports multiple notifications configuration, which is a pair of `who to alert` and `when to alert` form fields. UI mockup assumes one notification configuration. If possible, @mekanix could you make a component out of it to support multiple notifications ootb?

 * Server provides list of notification configurations in `/monitoring/api/notifications/config/` url. More details on format in docs: https://github.com/geosolutions-it/geonode/wiki/Monitoring:-Notifications#notification-list

 * Each notification configuration (https://github.com/geosolutions-it/geonode/wiki/Monitoring:-Notifications#notification-details) contains list of fields that should be rendered `fields` list. 
   * field name is stored in `field_name`.
   * field label can be constructed from `description`
   * unit can be extracted from `unit` field
   * if field definition provides list in `steps_calculated`, this should be used to construct selection/dropdown, otherwise text input should be displayed. If possible, validation should take into account `min_value` and `max_value`. 
   * currently set value is available in `current_value` field.
   * each field has `is_enabled` property, which tells if field is enabled. Currently this value is calculated in following way: field is enabled if `current_value` is not `None`. This may change in the future.

 Additionally, each notification configuration accepts list of emails in `emails` field. This field should be send as a list of emails joined with new line char (`\n`).
 
 Form should be submitted to the same url as configuration source (`/monitoring/api/notifications/config/{id}/`).
