### ISSUE TITLE
[monitoring] drop down select of services

### ISSUE THREAD

**Issue by mekanix** [geosolutions-it/geonode#205]

**Comment by cezio** [comment]
API endpoints:
 * list of services: ``http://geonode-dev-mon.geo-solutions.it/monitoring/api/services/``
 * list of resources: ``http://geonode-dev-mon.geo-solutions.it/monitoring/api/resources/``
 * list of ows services: ``http://geonode-dev-mon.geo-solutions.it/monitoring/api/ows_services/``
