### ISSUE TITLE
[monitoring] We need a Map widget that should show minimal geolocated stats by country

### ISSUE THREAD

**Issue by mekanix** [geosolutions-it/geonode#207]

**Comment by cezio** [comment]
API workflow:
 * metric name is ``request.country``.
 * you can get list of used country codes (labels in metric) from http://geonode-dev-mon.geo-solutions.it/monitoring/api/labels/?metric_name=request.country
 * when requesting data for the metric, ``http://geonode-dev-mon.geo-solutions.it/monitoring/api/metric_data/request.country/`` you should receive list of period,  each period's ``data`` element can have several items, like:
```
{
"valid_from": "2017-08-04T09:00:00",
    "data": [
        {
          "samples_count": 1,
          "val": "1.0000",
          "min": "1.0000",
          "max": "1.0000",
          "sum": "1.0000",
          "label": "IE",
          "metric_count": 1
        },
       {
          "samples_count": 215,
          "val": "215.0000",
          "min": "14.0000",
          "max": "15.0000",
          "sum": "215.0000",
          "label": "US",
          "metric_count": 15
         },
        { 
          "samples_count": 16,
          "val": "16.0000",
          "min": "1.0000",
          "max": "2.0000",
          "sum": "16.0000",
          "label": "IN",
          "metric_count": 11
        },
       {
          "samples_count": 356,
          "val": "356.0000",
          "min": "1.0000",
          "max": "40.0000",
          "sum": "356.0000",
          "label": "IT",
          "metric_count": 23
        }
      ],
    "valid_to": "2017-08-04T10:00:00"
}
```
properties:

 * ``label`` - code for a country
 * ``val`` - number of requests from that country

**Comment by mekanix** [comment]
Research https://www.npmjs.com/package/react-leaflet

**Comment by simboss** [comment]
@mekanix you might want to talk to the MapStore guys for directions on how to use leaflet for this.

**Comment by simboss** [comment]
@cezio I believe we are missing a Geometry to be used for the country in the country list in order to put this info on a map.

I would suggest to return also a coord (lat,lon) which the client can use to place something on the map.
I would want a circle with size and color made according to the metric we are showing.

**Comment by mekanix** [comment]
- React Leaflet research: #216

**Comment by simboss** [comment]
Notice that in the map mockup we are missing a legend, which is important for users.

**Comment by cezio** [comment]
Just thinking out loud here: do we need to return geometry here? Map is static svg, so if paths have country code in ``id``, they can be easily identify and styled in client side.

Or, I can calculate separate metric, with label composed of country code and stringified point, something like ``IT;POINT(8.01 12.0)``. This would need to be parsed in frontend.

**Comment by cezio** [comment]
#219 related (if not duplicate)
