### ISSUE TITLE
[monitoring] error list

### ISSUE THREAD

**Issue by mekanix** [geosolutions-it/geonode#208]

**Comment by mekanix** [comment]
* errors button in ui - should show list of exceptions (mockup 002)
 * list should be filtered by service and time, something like this: http://geonode-dev-mon.geo-solutions.it/monitoring/api/exceptions/?valid_from=2017-07-15&service=local-geonode
 * list should show:
    * timestamp, service, type of exception
    * when clicked, item should expand and show full stack trace
 * error rate chart should show response.errors.count metric, which is basically count of exceptions in period of time
   * assumption is when service returns 5xx error, it will also generate exception

**Comment by cezio** [comment]
#206 related
