### ISSUE TITLE
[monitoring] extract ows autodiscovery app to separate package

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode#249]
OWS autodiscovery (https://github.com/GeoNode/geonode/issues/3250) is available currently only on latest master branch of GeoNode. It doesn't use any new functionality and could be used with older GN versions. That's why it should be extracted from geonode's tree and distributed as separate package. 

#233 loosely related

**Comment by simboss** [comment]
@cezio make sure you add a useful description to tasks. This should be enough for someone to pick this work withouth having to do a brain dump from you :)

**Comment by cezio** [comment]
@simboss description updated

**Comment by cezio** [comment]
One more idea here: since ows endpoints are already in geonode core, and will be available presumably in next release, this application should be run with older geonode instances only. I'll add some checks in code and warning in documentation.
