### ISSUE TITLE
[monitoring] W*S Analytics issues

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#258]
On a new installation with GeoServer 2.12.x:
- W*S Analytics do not work at all

**Update**

* [x] in Geonode Layer Analytics layer selection is not providing adequate layer id for request (it looks like it's using element's index from array instead of layer id associated with it).
* [x] Table looks like hardcoded (maybe it's a matter to have layer selection corrected)
* [x] W*S layer analytics shows data, but not for selected layer and not for selected service (ows service above charts), however, most frequently accessed layers will show data, depending on interval selected

**Comment by cezio** [comment]
fixed in #273, #274 #275
