### ISSUE TITLE
[monitoring] Average Time Periods

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#259]
On a new installation with GeoServer 2.12.x:

- Trying to get averages for 1 Day or 1 Week do not work at all

**Comment by cezio** [comment]
There was an error in time window calculation (1h, 1d etc). time window was calculated in a way it would be aligned from midnight, so if you were querying around X:50 for last hour, actual time window would be from (X-1):00 to X:00. https://github.com/geosolutions-it/geonode/commit/585bcc8d02f47d3d5f1a387eb45fc69e091f5ecb.
