### ISSUE TITLE
[GeoServer-GeoNode-ext] Monitoring hibernate extension won't start after GWC REST upgrade

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#265]
Properties must define "gwc.prefix" otherwise GWC will clash with REST endpoints

**Comment by aaime** [comment]
This should solve the issue (even if, just running with your pull request on monitoring, I cannot reproduce anymore). But this one fixes the startup even without your pull request (which is still useful due to hibernate upgrades mind):

https://github.com/geoserver/geoserver/pull/2612
