### ISSUE TITLE
[GeoServer-GeoNode-ext] GeoFence won't start due to side effects of GWC REST upgrade

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#267]
GeoFence .properties; could not load anymore default placeholders (GEOSERVER_DATA_DIR, geofence.dir)

**Comment by simboss** [comment]
@afabiani GeoServer issue for this?

Anyway, I assigned to @etj

**Comment by aaime** [comment]
See discussion on the devel list, having multiple property placeholders is possible but they need to be set so that they are tolerant of keys not found and allow fallback. Not sure if the geofence one is already doing so.
