### ISSUE TITLE
[GeoServer-GeoNode-ext] GWC property placeholder breaking plugins

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#271]
GeoServer Property Placeholder and property gwc.prefix actually force to specify such property value to any plugin/extention willing to define its own Property Placeholder

**Comment by aaime** [comment]
Is this not a duplicate of a monitoring one too?

**Comment by afabiani** [comment]
Monitoring issue is a consequence of this which is more general. As a plugin making use of property placeholders currently Monitoring is also subjected to this.

**Comment by aaime** [comment]
This should fix things:
https://github.com/geoserver/geoserver/pull/2612
