### ISSUE TITLE
[GeoServer-GeoNode-ext] GWC tile operations not accessible from /geoserver/gwc

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#272]
Tile operations (truncate, seed, ...) are not more accessible from path

/geoserver/gwc

**Comment by aaime** [comment]
They seem to be there, for example this page works:

http://cloudsdi.geo-solutions.it/geoserver/gwc/rest/seed/sf:PrimitiveGeoFeature

Maybe I'm misunderstanding what you're saying? Could you provide an example?

**Comment by aaime** [comment]
Also, it could be related to the property configurer thing (like, if the gwc property is set to anything other than "gwc.context.suffix=gwc")
