### ISSUE TITLE
Layers analytics response.time metric

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/geonode#274]
Request for (geonode layers analytics)[
http://geonode-dev-mon.geo-solutions.it/monitoring/api/metric_data/response.time/?resource=114&last=604800&interval=604800] and (w*s layers analytics)[http://geonode-dev-mon.geo-solutions.it/monitoring/api/metric_data/response.time/?last=604800&interval=604800&resource=114&ows_service=WMS] have always empty data

**Comment by cezio** [comment]
fixed in 
https://github.com/geosolutions-it/geonode/commit/5f4990dadcf94556079ef2a984c7defd660750bf
https://github.com/geosolutions-it/geonode/commit/9d03813f7ef16155bb336fe9d3824b07fe91c6c6
https://github.com/geosolutions-it/geonode/commit/4506b3652646a9ef8147d3608ec31405f34d145a
