### ISSUE TITLE
implement user consent policy

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#289]
When the user decides to opt-out from tracking we have to keep his decision into account, and consequently stop saving its personal data (UUID, user-agent, IP location).

A policy message must be shown to first time visitors. We have to verify if / how a dedicated policy should be defined for european visitors (under european GDPR and cookie laws).
In case of anonymous users, their consent (true or false) must be temporary saved (session flag or cookie flag). In case of authenticated users it must be saved permanently as a user settings. It should be managed in a dedicated model without extendind the People model.

The user will be able to change its decision at a second time (through a proper form) and its settings will be updated accordingly.

**Comment by cezio** [comment]
What information should we keep here? Just a bool flag, or timestamp of consent? Also, should we store just current state or keep record of changes?

**Comment by giohappy** [comment]
The form should provide a flag to opt-in / opt-out from Analytics, and a link to the page containing the policies (what GeoNode tracks and how it processes data).
We don't need to keep the history, just the current consent.
