### ISSUE TITLE
Move the manual security sync button to the layer preview box (in layers list)

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#303]
I'd move the following button 

![image](https://user-images.githubusercontent.com/571129/51673278-e7400500-1fcd-11e9-9377-2e5b30975ed4.png)

to the layer preview box. 

![image](https://user-images.githubusercontent.com/571129/51673300-f4f58a80-1fcd-11e9-9aec-8d691113bc9c.png)

and inside the layer page:

![image](https://user-images.githubusercontent.com/571129/51673435-54539a80-1fce-11e9-86b9-aa3e5ee4a572.png)

**IT SHOULD ONLY BE VISIBLE if the layer is queed for a security synk.**

**I would totally remove the button from the upload window** because it's not clear what is its purpose, and I think it includes an action that is outside the scope of that window and cross cuts other contexts and actions.

**Comment by afabiani** [comment]
Done.
