### ISSUE TITLE
[Disasterrisk] - model, allow to associate (optionally) also an SLD to the Risk Analysis dymension association

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#31]
Currently the association between Risk Analysis and Dimension allows to select *only* the base layer hosting the features to filter out.

![image](https://cloud.githubusercontent.com/assets/1278021/23896447/bba1ea18-08a9-11e7-9886-06725b85531a.png)

It should be possible to associate to it also an SLD. This can be taken from the list of Styles associated to the layer (see GeoNode)

![image](https://cloud.githubusercontent.com/assets/1278021/23896474/d41851f4-08a9-11e7-85b3-7bf9fdfb8edc.png)

The Layer resource on GeoNode should already have a reference both to the Default Style and to Styles.

**Comment by afabiani** [comment]
We need to be sure that the management command also allows to specify the style name among the options

**Comment by afabiani** [comment]
There an exception when trying to parse the RiskAnalysis data

AttributeError at /risks/risk_data_extraction/loc/AF/ht/EQ/at/impact/an/2/

**Comment by cezio** [comment]
from our chat, it seems only name is needed for style in data view. should I remove other properties exported for style?
