### ISSUE TITLE
[Monitoring] Event types endpoint does not work

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#327]
We need event types to get resource count or other information filtered by event, example download.
Now requests on `/monitoring/api/event_types/` returns Page not found.
It should return list of allo event type as described in [documentation](https://github.com/geosolutions-it/geonode/wiki/Monitoring:-API#event-types)

**Comment by gioscarda** [comment]
[This PR ](https://github.com/geosolutions-it/geonode/pull/291) fixes it.
Test available at the `test_analytics` branch.
