### ISSUE TITLE
[Monitoring] Bad request with resource type url

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#329]
[Wiki](https://github.com/geosolutions-it/geonode/wiki/Monitoring:-API#resource) shows url as valid resource type.
Requests with resuorce_type equal to url returns an error.

Request
```
/monitoring/api/metric_data/request.count/?group_by=resource&last=86400&interval=86400&resource_type=url
```
Response
```
{"status": "error", "errors": {"resource_type": ["Select a valid choice. url is not one of the available choices."]}, "success": false}
```

**Comment by gioscarda** [comment]
The `url` resource type was not considered before [this PR](https://github.com/geosolutions-it/geonode/pull/291). Test available on the `test_analytics` branch.
