### ISSUE TITLE
[Disasterrisk] report on the RiskAnalysis data JSON also the param associated to dim axis

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#33]
If dimension has axis = x, the JSON should report layerAttribute = d1

If dimension has axis = y, the JSON should report layerAttribute = d2

and so on...

**Comment by cezio** [comment]
just to be clear: ``d1`` or ``dim1_value``?

**Comment by afabiani** [comment]
d1

**Comment by cezio** [comment]
I'm not sure where this should be available in ``riskAnalysisData``. I was thinking about putting it inside ``dimensions`` list:

```
'riskAnalysisData': {
   'data': {
      'dimensions': [
            {'abstract': ...,
             'layers': {..},
             'layerAttribute': 'd1',},
             ...
       ]
  }
}

```

But layerAttribute is stored in RiskAnalysisDymensionInfoAssociacion model, which can have different axis values and resulting layerAttributes. So this should be a list or mapping between names of columns in values and layer attributes, similar as in ``layers`` mapping.

@afabiani, what do you think?
