### ISSUE TITLE
[Monitoring] resource_type parameter is ignored with some requests

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#330]
Request ignores resource_type with the following parameter last, interval and resource_type

this request
`/monitoring/api/metric_data/request.count/?last=86400&interval=3600&resource_type=layer`
and this
`/monitoring/api/metric_data/request.count/?last=86400&interval=3600`
return the same results.

I would expect the count only for the resource type when it has been declared as param in the request.

**Comment by gioscarda** [comment]
This kind of filter was not implemented. I've introduced it in the `test_analytics` branch for testing.
