### ISSUE TITLE
[Monitoring] event_type is ignored on some requests

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#331]
event_type parameter has no effect on request.

Following requests returns same response:
```
/monitoring/api/metric_data/request.count/?group_by=resource&last=86400&interval=86400&resource_type=layer&event_type=download
```
```
/monitoring/api/metric_data/request.count/?group_by=resource&last=86400&interval=86400&resource_type=layer
```
if event_type is added to request it should return only values that match the event type

**Comment by gioscarda** [comment]
There is not `event_type` filter actually.
In [this PR](https://github.com/geosolutions-it/geonode/pull/291) it was introduced here

https://github.com/geosolutions-it/geonode/pull/291/files#diff-ef592a73aea0c24db7bf6a14ac41438fR774-R777

but it only add the `event_type_id=10` condition if the request has no `event_type` parameter (10='all').

I did some changes and I added a new `event_type` filter in the `test_analytics` branch to test it.
