### ISSUE TITLE
Define Events format 

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geonode#342]
The information we want to put inside the messages we are going to send to the centralized dashboards are identified in [this](https://docs.google.com/spreadsheets/d/1tPPX3kIXvKwR0tn6yLZtrc0E3Srao2YMb-yJn6f_svg/edit?usp=sharing) spreadsheet.

We need to document this properly and in relation to #343 define the format and protocol for sending them to the dashboard.

Some more info.

- we should use JSON
- I would be happy to use HTTPs with proper compression to reduce bandwidth

**Comment by gioscarda** [comment]
With reference to [this](https://docs.google.com/spreadsheets/d/1tPPX3kIXvKwR0tn6yLZtrc0E3Srao2YMb-yJn6f_svg/edit?usp=sharing) doc, we can define 4 event formats based on the information we are sending:
1. `OVERVIEW` --> global stats about GeoNode instance
```
{
  "auth_token": auth token,
  "instance": {
    "name": geonode instance HOSTNAME,
    "ip": geonode instance IP,
    "position": geonode instance GEOIP
  },
  "time": {
    "startTime": UTC now - 1 day
    "endTime": UTC now
  },
  "hits": total number of requests,
  "uniqueVisits": total number of unique sessions,
  "uniqueVisitors": total number of unique users,
  "registeredUsers": total number of registered users at the end time,
  "layers": total number of layers at the end time,
  "documents": total number of documents at the end time,
  "maps": total number of maps at the end time,
  "errors": total number of errors
}
```
2. `RESOURCES` --> detailed stas for each resource
```
{
  "auth_token": auth token,
  "instance": {
    "name": geonode instance HOSTNAME,
    "ip": geonode instance IP,
    "position": geonode instance GEOIP
  },
  "time": {
    "startTime": UTC now - 1 day
    "endTime": UTC now
  },
  "resources": [
    …
            {
                "type": resource type,
                "name": resource name,
                "url": resource URL,
                "hits": total number of requests about this resource,
                "uniqueVisits": total number of unique sessions about this resource,
                "uniqueVisitors": total number of unique users about this resource,
                "downloads": total number of resource downloads,
                "ogcHits": total number of OGC service requests about this resource,
                "publications": total number of publication events (*)
            },
    …
  ]
}
```
(*) For most resources this value could always be equal to 1, is this a meaningful data?

3. `COUNTRIES` -->  detailed stas for each country
```
{
  "auth_token": auth token,
  "instance": {
    "name": geonode instance HOSTNAME,
    "ip": geonode instance IP,
    "position": geonode instance GEOIP
  },
  "time": {
    "startTime": UTC now - 1 day
    "endTime": UTC now
  },
  "countries": [
    …
            {
                "name": country name,
                "hits": total number of requests about the country
            },
    …
  ]
}
```
4. `UA FAMILIES` --> detailed stas for each UA Family
```
{
  "auth_token": auth token,
  "instance": {
    "name": geonode instance HOSTNAME,
    "ip": geonode instance IP,
    "position": geonode instance GEOIP
  },
  "time": {
    "startTime": UTC now - 1 day
    "endTime": UTC now
  },
  "uaFamily": [
    …
            {
                "name": UA family name
                "hits": total number of requests about the UA family
            },
    …
  ]
}
```
Formats `2`, `3` and `4` contain arrays so they require a [split filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-split.html#_description_142), on the Logstash side, which creates an event for each element of the array.

Each message will also contain an `auth_token` which will be used by Logstash to authorize the request.

Messages will be sent via `TCP` in `JSON` format with a `gzip`  compression (ref. #367 ).

**Comment by gioscarda** [comment]
We have to avoid the following fields:
- `auth_token` --> allowed instances will be filtered through a firewall on the server side
- `position` --> Elastic does not need this information, it will retrieve the client position from the IP through the `Geoip filter plugin`

**Comment by randomorder** [comment]
can we close this one @gioscarda ?

**Comment by gioscarda** [comment]
@randomorder yes we can
