### ISSUE TITLE
Define how to extend GeoNode monitoring plugin to send message to Centralized Dashboard 

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geonode#345]
The idea here is to extend the GeoNode Monitoring plugin to account for the possibility to send condensed information to the CD. 

We do not want to send all the information to CD with individual granularity but rather a simplified version of the collected stats over *the last hour* as per the information defined [here](https://docs.google.com/spreadsheets/d/1tPPX3kIXvKwR0tn6yLZtrc0E3Srao2YMb-yJn6f_svg/edit#gid=1261903425).

I would want the monitoring plugin to push data the CD once it is configured to do. It should collect data as per [this](https://docs.google.com/spreadsheets/d/1tPPX3kIXvKwR0tn6yLZtrc0E3Srao2YMb-yJn6f_svg/edit#gid=1261903425) definition every hour and then send it the CD in the format we define in #342 and with the protocol defined in #343. We should also respect what we define here #344.

**Comment by randomorder** [comment]
can we close this one @gioscarda ?

**Comment by gioscarda** [comment]
@randomorder yes we can
