### ISSUE TITLE
Metrics response.error.count returns empty data

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#355]
If we compare response.error.count and exceptions endpoint we have different results (response.error.count data is always empty)
`/monitoring/api/metric_data/response.error.count/?last=86400&interval=86400`
`/monitoring/api/exceptions/?last=86400&interval=86400`

Is this correct?
Should exceptions and error count return at least the same number of errors?

response.error.count create empty charts in Software performance

![2019-09-02 12_19_27-Window](https://user-images.githubusercontent.com/19175505/64107997-05e45680-cd7c-11e9-99f8-b6739b6b442a.png)

**Comment by gioscarda** [comment]
Resolved.
This issue can be closed.
