### ISSUE TITLE
mem.usage.percent and cpu.usage.percent return empty data

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/geonode#359]
See Hardware performance in the UI, all the charts are empty for every time range.
![2019-09-02 14_05_06-Window](https://user-images.githubusercontent.com/19175505/64113755-6d55d280-cd8b-11e9-9021-c5348f1c0ebc.png)

**Comment by gioscarda** [comment]
Resolved.
This issue can be closed.
