### ISSUE TITLE
Investigation needed about the gzip_lines plugin used by Logstash to parse compressed JSON

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/geonode#367]
We have to investigate about the [gzip_lines logstash plugin](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-gzip_lines.html) in order to send compressed JSON to the centralized analytics server.

I did not find much information about that in the internet (except [this](https://stackoverflow.com/questions/54300790/how-to-read-gzipped-json-for-logstash-input) unresolved stackoverflow question) and no tests have been made concerning this plugin. @randomorder could you install it on the test server so that I can do some tests?

**Comment by randomorder** [comment]
plugin installed
```
docker exec -it docker-elk_logstash_1 bash
cd /usr/share/logstash/bin/
logstash-plugin install logstash-codec-gzip_lines
exit
```

**Comment by simboss** [comment]
@gioscarda let us know if the plugin works and if we can close this one.

**Comment by gioscarda** [comment]
@simboss the plugin works fine. We can close this issue.
Thank you @randomorder
