### ISSUE TITLE
[Disasterrisks] - Forced to specify at least one additional layer on admin dashboard

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#40]
![image](https://cloud.githubusercontent.com/assets/1278021/24097394/e6ff6422-0d65-11e7-86c5-c16752168680.png)

**Comment by cezio** [comment]
should be fixed with https://github.com/geosolutions-it/geonode/pull/41/commits/34bb7b78b5b8d8a71701775c567df5b618b501a0
