### ISSUE TITLE
Maps layers don't show up inside the map page even if they're correctly saved inside the map config

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#408]
Reported in https://github.com/mapstand/hub-issues/issues/39

**Comment by simboss** [comment]
I would want to see an analysis and a proposal before doing anything @afabiani .

**Comment by afabiani** [comment]
Easy fix, the problem is just related to some missing title on html template

**Comment by simboss** [comment]
is this mapstand related or is it a generic issue?

**Comment by afabiani** [comment]
Generic GeoNode one
