### ISSUE TITLE
LIKE filter on layer download doesn't let setting a pattern value

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#409]
Reported in https://github.com/mapstand/hub-issues/issues/30

**Comment by afabiani** [comment]
Fix on GeoNode available [here](https://github.com/GeoNode/geonode/pull/5417)

**Comment by giohappy** [comment]
@afabiani actually the user expects the LIKE filter to download all data matching the filter (and possibly with the ability to enter the % manually), not as a filter for the suggestion of values.

In brief users report a misleading behaviour when compared to the LIKE filter inside MapStore.
