### ISSUE TITLE
Centralized Dashboard - django-celery errors

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#411]
It looks like django-celery and Celery are having troubles with CONN_MAX_AGE parameters.

The problem is that by removing this parameter, they also won't release connections suddenly causing problems to GeoNode itself.

We'll need to figure out an alternative way to dispatch the messages.

**Comment by afabiani** [comment]
Was able to run dispatcher through cron and management commands

**Comment by randomorder** [comment]
@afabiani please investigate how to avoid using CRON and do everything from GeoNode GUI

**Comment by afabiani** [comment]
@simboss @randomorder my proposal is the following one:

1. get rid of "django-celery" which is really not useful. The "producer" interval will be set through the settings, easily, and it will be by default 1 hour.

2. the "consumer", currently, listens to the channel (by default a sqllite db). As soon as new messages are enqueued, it tries to send them to logstash. In case the send fails, it waits for a certain amount of time and makes some retries. After "x" retries, configurable, the message is discarded. The length of the queue is also configurable via the settings.
The problem is that new messages from the "producer" actually have "start-time" set to the last "successfull" send and not to the configured "interval". Therefore, if any failure occurs for some reason, and the producer is awaken, the next bunch of messages will contain duplicated events.
My proposal is to update the "producer" in order to always set the "start-time" and "end-time" coherently to the send interval.
