### ISSUE TITLE
Split permissions assignment and GeoFence rules for WFS and WFS-T requests

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#412]
When "Download" permissions is enabled for a layer all the WFS service requests are enabled for it, including WFS-T ones. This means that users authorized to download and navigate the features attributes, are also able to edit the features. This is clearly not desired!

The proposal is to **add a DENY rule for WFS-T requests by default**.

A step further would be to **add a new permission block inside GeoNode to grant editing permissions**, along with download permissions. If editing permissions are granted we will change the WFS-T rule to ALLOW (or we could simply remove the rule since the default ALLOW for * request would win).

Example:

![image](https://user-images.githubusercontent.com/571129/71107175-e5bc9400-21c0-11ea-8a24-786be42d971d.png)

**Comment by afabiani** [comment]
See https://github.com/GeoNode/geonode/issues/5779
