### ISSUE TITLE
Widgets on maps are not retained on reload

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#417]
Widgets on the maps are lost when the map is reopened.

Steps to reproduce (either on master or dev server):

1. create a new map
2. add a layer
2. add whatever widget for the layer (text, table, etc.)
3. save the map
4. reopen the map -> no widgets are shown

Something similar is also reported in [an issue](https://github.com/mapstand/hub-issues/issues/47) from MapStand.

**Comment by afabiani** [comment]
ref. https://github.com/GeoNode/geonode/issues/5485
