### ISSUE TITLE
Error when saving a map

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#418]
Saving [this map](https://master.demo.geonode.org/maps/1863/edit) on master server gives the following error:

`{"detail":"Traceback (most recent call last):\n File \"/usr/local/lib/python2.7/site-packages/mapstore2_adapter/plugins/serializers.py\", line 185, in set_geonode_map\n lyr_name)\n File \"/usr/src/geonode/geonode/layers/views.py\", line 376, in layer_detail\n PERMISSION_MSG_VIEW)\n File \"/usr/src/geonode/geonode/layers/views.py\", line 187, in _resolve_layer\n *kwargs)\n File \"/usr/src/geonode/geonode/utils.py\", line 840, in resolve_object\n obj = get_object_or_404(model, *query)\n File \"/usr/local/lib/python2.7/site-packages/django/shortcuts.py\", line 85, in get_object_or_404\n return queryset.get(*args, **kwargs)\n File \"/usr/local/lib/python2.7/site-packages/django/db/models/query.py\", line 384, in get\n (self.model._meta.object_name, num)\nMultipleObjectsReturned: get() returned more than one Layer -- it returned 2!\n"}
`

**Comment by afabiani** [comment]
ref. https://github.com/GeoNode/geonode/issues/5486

**Comment by afabiani** [comment]
PR https://github.com/GeoNode/geonode/pull/5492
