### ISSUE TITLE
documentation is missing for "Install GeoNode for Development" 

### ISSUE THREAD

**Issue by maabdelghaffar** [geosolutions-it/geonode#420]
**Description:**
Currently there is no documentation regarding the required steps to install GeoNode for development purpose under the DEVELOPING section in the documentation pages: http://docs.geonode.org/en/2.10.x/

**Solution:**
To document the necessary steps of installation (prerequisites and tools) for both GeoNode Project and Core sub-sections under DEVELOPING head-section. Also to provide a method to verify the installation process. 

**Notes:**
The description needs to be as simple/clear as possible

**Comment by maabdelghaffar** [comment]
@afabiani can you please confirm which operating systems and versions will be supported for the DEVELOPING section? I can see that the old materials targeted Ubuntu 12.04 and Windows 2008r2!

**Comment by afabiani** [comment]
@maabdelghaffar Ubuntu 18+

**Comment by maabdelghaffar** [comment]
During GeoNode-Project installation for development, 2 errors encountered as follows while executing  "paver setup" as follows: 

1. ConnectTimeout: HTTPSConnectionPool(host='build.geo-solutions.it', port=443): Max retries exceeded with url: /geonode/geoserver/latest/geoserver-2.15.2.war (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f71a0ce6050>, 'Connection to build.geo-solutions.it timed out. (connect timeout=10)'))

2. Error: Invalid or corrupt jarfile jetty-runner-9.4.7.v20170914.jar
--------------------------------------------------------------

**The reasons:** 

1. Either build.geo-solutions.it was down the whole day, or the url wasn't set properly. I found that @afabiani changed the geoserver from 2.15.2 to 2.15.3. I tried that but it didn't fix the issue. so most probably the server was down.

2. The jetty-runner url was outdated/not-found

**The fix:**
1. As a temporarily fix, I had to find another source for the Geoserver war. so I got it from: https://sourceforge.net/projects/geoserver/files/GeoServer/2.15.3/geoserver-2.15.3-war.zip.
Another solution is to copy the Geoserver i have installed earlier. however I am not sure how it would react later.

2. Got a replacement for the jetty-runner from: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar

After that I had to change it inside my local **dev_config.yml** to test the paver setup and start and see the results if worked fine  

A further discussion with @afabiani on Monday to be followed

**Comment by maabdelghaffar** [comment]
Server was down as @afabiani indicated and now i reverted to the build.geo-solutions mirror.

**Comment by maabdelghaffar** [comment]
while the buid.geo-solutions issue is fixed, still the http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar  is broken so i had to still use the replacement one: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar

**Comment by maabdelghaffar** [comment]
@afabiani  Installation is tested and typos are fixed with adding some more details and screenshots. To be merged with other fixes related to Developing documentation details and improvements.

**Comment by afabiani** [comment]
@maabdelghaffar can you create another PR on official repo please?

**Comment by maabdelghaffar** [comment]
@afabiani created  #5540
