### ISSUE TITLE
test GeoNode with GeoServer 2.16.2

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#428]

**Comment by randomorder** [comment]
Artifacts here
https://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.16.2/lastSuccessfulBuild/artifact/geoserver/web-app/target/geoserver.war

GeoServers is starting on my local machine. Testing with GeoNode Required.

**Comment by randomorder** [comment]
tested, right? can I close @afabiani ?

**Comment by afabiani** [comment]
Tested and found three known issues:

 - Notification module brakes feature edit (fixed)
 - Status monitoring does not return values anymore via REST (fixed)
 - Backup and Restore plugin is not able to restore SLDs anymore (ongoing)

**Comment by giohappy** [comment]
well, the latest issue also affects GS 2.15.3, so I wouldn't consider this an issue strictly related to the upgrade.
