### ISSUE TITLE
set up build for GeoServer 2.16.2

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#429]
https://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.16.2/configure

**Comment by randomorder** [comment]
@afabiani  I pushed a temptative update for the geoserver poms for 2.16.2 [here](https://github.com/randomorder/geoserver-geonode-ext/tree/2.16.2)

**Comment by randomorder** [comment]
Jenkins job [here](https://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.16.2/1/console)

**Comment by randomorder** [comment]
@afabiani 
[I kept](https://github.com/randomorder/geoserver-geonode-ext/blob/2.16.2/geoserver/pom.xml#L903) the GF version used on the master branch because GeoServer 2.16.2 is using [an older version](https://github.com/geoserver/geoserver/blob/2.16.x/src/pom.xml#L1990). Hope that is ok

**Comment by randomorder** [comment]
I'll set up a build for 2.16.x as well since we may actually want to test and fix some issues in GeoServer. When we're happy with it we can make eventually an extra 2.16.2.1 release and use that on GeoNode

**Comment by simboss** [comment]
my suggestion as well.

**Comment by simboss** [comment]
@randomorder @afabiani ?

**Comment by afabiani** [comment]
There's altready 2.16.x and 2.17.0 as far as I know
