### ISSUE TITLE
GeoServer CSRF issue

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#431]
we had to disable anti-CSRF in Geoserver to have GeoNode working. Investigate why

This happened on 2.15.4 as well as 2.16.2

**Comment by randomorder** [comment]
I think we need to open a JIRA for this one... I can't believe we are the only one facing this issue
1 - Replicate
2 - open JIRA

**Comment by simboss** [comment]
@randomorder is right here, having to disable something that was added to geoserver for security reasons (that is because penetration testing reported this as an issue) to make geonode work is not good.

We need to understand what's going south here and then lay out a plan.

**Comment by afabiani** [comment]
Uhm not fully agree. This CORS functionality protects only the GeoServer admin GUI, not really something that concerns GeoNode, except maybe for production configuration.

My opinion is that this is something that should be more investigated on GeoServer side.

**Comment by simboss** [comment]
@afabiani this is the feedback we need and this is why this issue is needed.

Please, describe better how this is impacting GeoNode and what you had to disable so that we can open a discussion with the GeoServer devs as well.

**Comment by giohappy** [comment]
from my experience with thi issue it also impatcs Geoserver GUI outside of GeoNode, isn't it @afabiani? I had problems with loading a Shapefile when creating a new store, and I was using local Geoserver running on Tomcat. The issue made the "browse" widget stop working.
I really would like to understand if, outside of GeoNode, this hasn't been noticed by anyone else.

**Comment by simboss** [comment]
@giohappy is there a JIRA for this?

**Comment by afabiani** [comment]
GeoNode is not affected at all by this issue. The problem appears only when trying to access the GeoServer admin GUI. The CORS protection seems to be a little buggy in GeoServer. It basically allows you to login and access any "first level" page rendered by wicket, but blocks any internal switch, like tabs and search filters.
I hadn't time yet to try a vanilla GeoServer, but, most likely, this is something that affects the GeoServer implementation.
Ad @giohappy said, this issue occurs either by accessing GeoServer gui directly from Tomcat or under an httpd proxy.

**Comment by giohappy** [comment]
@simboss do you want me to replicate and report the issue or shall we wait @afabiani to do this? In case I will have to restore my local setup to the affected Geoserver versions.

**Comment by randomorder** [comment]
> @giohappy is there a JIRA for this?

https://osgeo-org.atlassian.net/browse/GEOS-9353
Is this the same issue you had @giohappy ?

**Comment by giohappy** [comment]
@randomorder it seems very similar to what I was facing, although I wasn't behind any proxy (neither Nginx nor Docker's). When I tried to open the Browse widget to set the Shapefile path I could see similar errors inside browser console, but I didn't investigated much. After that error a lot of downstream errors happened and I wasn't able to create the new store.
