### ISSUE TITLE
centralized dashboard event shipping failure

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#436]
client side reporting an issue with events shiping and keep re-sending the same events over and over

**Comment by simboss** [comment]
is this for @afabiani to investigate or for you @randomorder ?

**Comment by randomorder** [comment]
both of us, we're working on it

**Comment by randomorder** [comment]
`[2020-02-13T10:35:13,083][ERROR][logstash.inputs.tcp      ] Error in Netty pipeline: org.jruby.exceptions.SystemCallError: (EPIPE) Broken pipe - Unexpected end of ZLIB input stream
`

**Comment by afabiani** [comment]
Seems like it was some record corrupted on the producer db.

Until now everything seems working fine.
