### ISSUE TITLE
Filter requests in GeoNolde Monitoring / Analytics?

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#444]
Is it possible to filter aout a given user /group / IP address so that is not taken into account by the monitoring system?
For instance, our Uptime service for the GeoNode instances (Heartbeat) is pinging all of the geonodes every 30 seconds and is "polluting" the stats:
![Screenshot from 2020-03-05 11-39-59.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/95dcdc69-5183-4674-b2ab-cf02e030dc1d)

Yes, heartbeat it is located in France :-)

**Comment by afabiani** [comment]
Currently not, sorry :(
