### ISSUE TITLE
Centralized Dashboard - meaning of unique visits / visitors

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/geonode#446]
Can you please help me understang the meaning of those fields in the `resource` events?
![image.png](https://images.zenhubusercontent.com/5cd59eb418690954352b7621/a19899f6-8130-4f6f-8137-bbbc8c91c80f)

**Comment by afabiani** [comment]
"unique_visitors" is the number of visitors distinct, excluding anonymous users.

"unique_visits" is the number of unique sessions, including anonymous ones. Whenever a user closes the web browser, a new visit might be computed as unique during the time interval.

**Comment by randomorder** [comment]
ok, thanks
