### ISSUE TITLE
Radiobox for time attribute selection doesn't appear

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#453]
During the upload of a vector file id a date column is found the user is given the option to configure the layer as a vector time series.
The configuration step asks the user to select the time attribute column, falgging a checbox on the side of the column name. The checkbox doesn't appear for GeoNode master, while it works fine on GeoNode 2.10.x

**GeoNode 2.10.x**
![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/442c0b57-62d1-418e-819d-9219c792a5d9)

**GeoNode master**
![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/018b62cf-b9ee-4bd3-bb58-107c129c65a1)

**Comment by afabiani** [comment]
Should be fixed by https://github.com/GeoNode/geonode/commit/4d0a7e5b9ca49f9c4b554d8ad06a230cee219f98

**Comment by giohappy** [comment]
@afabiani it was assigned to @petrus7 and he already have a PR for that. Please avoid taking action without coordination

**Comment by giohappy** [comment]
fixed in https://github.com/GeoNode/geonode/pull/5961
