### ISSUE TITLE
Collect metrics jobs pile up and cause exhaustion of memory

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#457]
This has been reported both for [Malawi](https://github.com/geosolutions-it/support/issues/483) and [UNESCO](https://github.com/geosolutions-it/support/issues/493)

The spwaned collect_metrics commands pile up and consumes all the available RAM.

**Comment by afabiani** [comment]
@giohappy a locking mechanism like this one could easily fix the issue

http://docs.celeryproject.org/en/latest/tutorials/task-cookbook.html#ensuring-a-task-is-only-executed-one-at-a-time

its implementation should take no more than a few hours.

**Comment by giohappy** [comment]
go ahead with the locking

**Comment by afabiani** [comment]
A PR has been issued [here](https://github.com/GeoNode/geonode/pull/5984)
