### ISSUE TITLE
Thumbnails are not generated with GeoServer 2.16.x and GeoNode 3

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geonode#461]
Thumbnails are not generated; this is probably caused by the unique remaining custom module on geoserver-ext which are a bunch of rest endpoints used by GeoNode to let GeoServer creating the thumbnail. The call gives an "HTTP Status 404 – Not Found" error. It is worth noticing that the print still works. This must be further investigated but I guess it shouldn't be a big deal to fix it somehow on geoserver-ext.

**Comment by simboss** [comment]
Apparently this is due to a missing dependency.

Please, @afabiani double check and let us know.

**Comment by afabiani** [comment]
Temporarily restored the missing dependency.
Render thumbnail with 2.16.x now it is working again.
