### ISSUE TITLE
It's not clear which kind of files are supported in Geolimits configuration

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#465]
![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/9914033b-83c9-4c83-93d9-e3932e257aab)

**Comment by afabiani** [comment]
zip files only containing a shapefile.
If the zip file contains a .prj, you don't have to specify the SRID, it will be automatically set on the proj4 defs.

**Comment by simboss** [comment]
@afabiani it is not a question it is a request to add this information somehow in the UI.

A tooltip, some text, anything...

**Comment by afabiani** [comment]
ref. https://github.com/GeoNode/geonode/issues/5978
