### ISSUE TITLE
Build Geoserver 2.15.4 and 2.16.2 for GeoNode to incorporate fixes to gs-notification

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#467]
As soon as the gs-notification with fixes from PR https://github.com/geoserver/geoserver/pull/4167 is built we need to run:

- [x] Jenkins build of WARs for 2.15.4 and 2.16.2
- [x] geonode/geoserver :215.4 and geonode/geoserver :2.16.2 Docker imges

**Comment by afabiani** [comment]
Done
