### ISSUE TITLE
Create HipTest project for GeoNode testing

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#470]
Starting from the spreadsheet we want to start a HipTest (now CucumberStudio) project for GeoNode and port the test over there.

**Comment by ElenaGallo** [comment]
@giohappy [Here](https://studio.cucumber.io/projects/192843/test-plan/folders/1410325) I started a new CucumberStudio project for GeoNode

**Comment by giohappy** [comment]
cool thanks!
