### ISSUE TITLE
Port to Python 3 code for shipping events to centralized dashboard

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/geonode#475]
Apparently the code we wrote for shipping events to the centralized dashboard has not been ported over to Python 3.

We need this code to be available asap in order to be allowed to ship events to the CD for the instances we want to monitor.

@afabiani @giohappy this is a priority.

**Comment by afabiani** [comment]
It will need 2/3 days to port the **logstash** module to py3 only.

**Comment by simboss** [comment]
Is this logstash module something inside GeoNode or an external modules?

This is not clear to me, please, provide more information.

**Comment by afabiani** [comment]
It is part of a repo containing GeoNode extensions which are not part of the core and that can be installed separately

https://github.com/GeoNode/geonode-contribs

like:

 - LDAP support
 - risks extension we made for Afghanistan
 - worldmap client

and so on...

**Comment by simboss** [comment]
@giohappy I would assign this one to @abulojoshua1 if he is free right now.

Please, check with @afabiani as there are also other issues to be worked in terms of improving the monitoring modules. Let's review together.

**Comment by afabiani** [comment]
Done
