### ISSUE TITLE
Prevent integrity errors on singleton model save

### ISSUE THREAD

**Issue by petrus7** [geosolutions-it/geonode#477]
This bug was not confirmed by app usage, I spotted it browsing the code

https://github.com/GeoNode/geonode/blob/fd396deb39a7aa434991cdf238f915be2e90a9b1/geonode/singleton.py#L44

This will throw IntegrityError with duplicated key when force_insert:True is present in kwargs. This key is there when ones uses Manager.create(), and maybe some other time.

**Comment by giohappy** [comment]
ok @petrus7 please submit a PR on GeoNode upstream for this.

**Comment by petrus7** [comment]
the fix for that is: 
```
def save(self, *args, **kwargs):
        self.pk = 1
        kwargs.update({force_insert:False})
        super().save(*args, **kwargs)
```

**Comment by giohappy** [comment]
please submit a PR for this, when you're done with the other tasks.

**Comment by petrus7** [comment]
@giohappy 
it was already fixed:
https://github.com/GeoNode/geonode/blob/master/geonode/singleton.py
