### ISSUE TITLE
[GeoNode Project Docker] docker-compose.development.yml stale -> Django and Celery services keep restarting

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#479]
@afabiani I've tried running a geonode-project with default configurations, and something doesn't work.

1) Django and Celery services keeps restarting. See image below, which shows an excerpt of what happens in a loop:

Using master branch of [upstream repo](https://github.com/GeoNode/geonode-project) 
`docker-compose -f docker-compose.development.yml up`

**I suspect the problem is a misalignment between `entrypoint.sh`, which expects `$UWSGI_CMD` and `$CELERY_CMD`, and docker-compose.development.yml.** 

![image](https://user-images.githubusercontent.com/571129/91430639-7fb00280-e85f-11ea-8da6-73ff23259345.png)

**Comment by afabiani** [comment]
@giohappy that should be fixed now. You will need to update your geonode project too with the latest commits.
