### ISSUE TITLE
Port upstream the documentation about the improved setup of memcached and celery done for IGAD

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#537]
https://docs.google.com/document/d/1DQn96wkIRR6fHiEu2H8zonXnEoFiAeipUKPspP7unbg/edit#heading=h.75ibmbclh0vi

**Comment by afabiani** [comment]
@giohappy I prepared the Pull Requests here:

 - [How to setup rabbitmq, supervisor and memcached in order to fully enable async workers](https://github.com/GeoNode/documentation/pull/68)

 - [How to Upgrade from 2.10.x / 3.0](https://github.com/GeoNode/documentation/pull/69)
