### ISSUE TITLE
[Disasterrisk] Further Resources are not shown in JSON

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#62]
e.g. 
http://disasterrisk-af.geo-solutions.it/risks/risk_data_extraction/loc/AF32/ht/EQ/at/impact/an/3/

should have at least 1 resource available but currently the json opbject appears to be empty

```
furtherResources: {analysisType: [], hazardType: []}
```

**Comment by cezio** [comment]
I'm afraid there was no m2m connection in db for analysis type/further resource. Connection table was completely empty. I've added 4 connections, and this element shows correctly now.
