### ISSUE TITLE
[Disasterrisk] General optimization

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#69]
- [x] Enable GZIP compression
 - [x] Refine Geometries
 - [ ] General code optimizations...
 - [ ] include layer/SQLView creation in ``createriskanalysis`` command
 - [x] caching data views

**Comment by afabiani** [comment]
- Reduce JSON sent by endpoints where possible and where it is not necessary

**Comment by cezio** [comment]
nginx configuration:

```
server {
....
        gzip on;
        gzip_min_length 1000;
        gzip_types text/plain text/html application/json application/xml text/css text/javascript;
        gzip_comp_level 4;
        etag on;
        location @uwsgi {
                etag off;
                uwsgi_pass  geonode-risk;
                include     uwsgi_params;
                uwsgi_read_timeout 300s;
        }
     ...
}
```
 will gzip text responses over 1k chars, and add etag for all non-uwsgi responses.

**Comment by cezio** [comment]
quick benchmark:

gzip **off** cold cache: 60 requests/ **5.2 MB** / finish: **14.02** / DOMContentLoaded 11.62 / Load: 12.90s
gzip **off** cache 60 requests/ 216 KB / Finish: 5.54s DOMContentLoaded: 1.74s / Load: 2.27s

gzip **on** cold cache: 60 requests/ **1.9 MB** / Finish: **6.08** / load: 4.97 / DOMContentLoaded: 4.88
gzip **on** cache: 60 requests 84.3 KB / Finish: 5.43 s / DOMContentLoaded 1.61 s / Load: 2.17 s

so, cold cache request gets most of benefit, subsequent requests load slightly quicker with gzip (but difference is very small). I could add expires header, but i don't think we should do now - statics change quite often. We could enable this after production deployment.

**Comment by cezio** [comment]
We also could add expires header for json responses. Dataset is pretty static, so the same request should return the same response.

**Comment by kappu72** [comment]
in risksAnalysisDataView.riskAnalysisData.data.dimensions[n].layers[dim val]. layerAttribute  we repeat for all dimension values same layerAttribute, I guess we can have just risksAnalysisDataView.riskAnalysisData.data.dimensions[n].layerAttribute

**Comment by cezio** [comment]
I've added caching headers to json responses. deployed on old vm

**Comment by cezio** [comment]
>  I guess we can have just risksAnalysisDataView.riskAnalysisData.data.dimensions[n].layerAttribute

Yes, for current data set this can be done. I'm not sure if we should do this, because model allows several axes in dimension
