### ISSUE TITLE
Abstract error on a map preview

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode#692]
The abstract of a map is saved incorrectly, without images and without the correct layout

**How to Reproduce**
- Open [this map](https://master.demo.geonode.org/maps/667) 
- follow the steps of the video:
![sie](https://user-images.githubusercontent.com/56537133/109837222-3d6be180-7c45-11eb-8e45-8827a3ab705f.gif)

*Expected result*
The abstract of the map is displayed correctly, as it does for layers.
 An example of the correct abstract of a level follows:
![layer abstarct](https://user-images.githubusercontent.com/56537133/109837242-42309580-7c45-11eb-9faa-0b8840bf7664.png)

**Comment by giohappy** [comment]
@afabiani didn't you fix the preview fields also for maps?

**Comment by afabiani** [comment]
@giohappy I tought so... let me check

**Comment by afabiani** [comment]
@giohappy in the metadata update view for maps there's an explicit `strip_tags` function call when saving the abstract

see [here](https://github.com/GeoNode/geonode/blob/master/geonode/maps/views.py#L287)

If I remove that one, the HTML content will be saved correctly and therefore displayed as expected.

Do you know any reason why that function has been called here?

**Comment by giohappy** [comment]
That line dates back at least to [2014](https://github.com/GeoNode/geonode/tree/375226f188692c551a7c8756a10e048dbe151e28).
I don't have any idea why it was introduced. It shouldn't be placed there now, btw it could have been used for the raw_* fields instead of the custom regex :)

**Comment by afabiani** [comment]
Ok, removed it. Going to rebuild master.demo

**Comment by giohappy** [comment]
Why didn't you remove it for title too?

**Comment by afabiani** [comment]
becouse we don't have a "raw_title" currently

**Comment by giohappy** [comment]
I know but we don't have an HTML title niether :)
Otherwise it should be done for any field....

**Comment by afabiani** [comment]
removed

**Comment by afabiani** [comment]
@ElenaGallo you can try again now

**Comment by ElenaGallo** [comment]
@afabiani @giohappy now it works fine.
