### ISSUE TITLE
Upgrade GeoNode to Geoserver 2.18.x for 3.2.x branch and to 2.19.x for 3.3.x branch

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#756]
3.2.x and 3.3.x must upgrade their Geoserver when it will be available, to incorporate recent fixes to Geoserver.

**Comment by giohappy** [comment]
@simboss some recent fixes, like [this](https://github.com/geosolutions-it/support/issues/1551), landed in 2.18.x.
We must take a decision if we want to upgrade:

 - GeoNode 3.2.x: to provide the fixes to 3.2.x too (e.g. for MapStand)
 - GeoNode 3.3.x: [upgrade to 2.19?](https://github.com/geosolutions-it/geonode/issues/792) or keep 2.18.x
 - GeoNode master: [upgrade to 2.19?](https://github.com/geosolutions-it/geonode/issues/792)

**Comment by randomorder** [comment]
> @simboss some recent fixes, like [this](https://github.com/geosolutions-it/support/issues/1551), landed in 2.18.x.
> We must take a decision if we want to upgrade:
> 
> * GeoNode 3.2.x: to provide the fixes to 3.2.x too (e.g. for MapStand)
> * GeoNode 3.3.x: [upgrade to 2.19](https://github.com/geosolutions-it/geonode/issues/792) or keep 2.18.x?
> * GeoNode master: [upgrade to 2.19](https://github.com/geosolutions-it/geonode/issues/792)

Correct me if I am wrong @giohappy :
3.3.x and Master should use GeoServer 2.19.x. GeoPackage plkugin must be added
3.2.x should be updated to the latest nightly of 2.18.x

**Comment by simboss** [comment]
@randomorder correct

**Comment by lpasquali** [comment]
To recap I was given this as priority:
- 3.3.x and 2.19.x (add gpkg plugin)
- 3.2.x and 2.18.x 
- master to 2.19.x (add gpkg plugin) will then done and logged in dedicated issue #792

**Comment by giohappy** [comment]
@randomorder @etj please liaise to complete both the upgrades.

**Comment by etj** [comment]
I guess this link to dropbox  https://github.com/GeoNode/geonode-project/blob/3.2.x/docker/geoserver/Dockerfile#L14 
should be pointing to somewhere to the new s3 bucket containing the geoserver-geonode build.

@randomorder is the build server already configured to deploy according to the new directory hierarchy?

**Comment by randomorder** [comment]
we'll use S3 for the artifacts from now on @etj @lpasquali

**Comment by lpasquali** [comment]
for 3.2.x 
created branches:
- https://github.com/GeoNode/geoserver-geonode-ext/tree/2.18.x/geoserver
- https://github.com/GeoNode/data-docker/tree/2.18.x
- https://github.com/GeoNode/geoserver-docker/tree/2.18.x

**Comment by lpasquali** [comment]
PR for geonode and geonode-project here:

https://github.com/GeoNode/geonode/pull/8132

https://github.com/GeoNode/geonode-project/pull/237

**Comment by lpasquali** [comment]
documentation of the (simplified by this work) process: https://github.com/geosolutions-it/DevOps/wiki/Guide-to-upgrade-GeoServer-for-GeoNode

**Comment by randomorder** [comment]
moving on with the upgrade of GeoServer on [https://development.demo.geonode.org/](https://development.demo.geonode.org/)

**Comment by randomorder** [comment]
did you test on your end @lpasquali ? If that's the case pass the ball to @giohappy and @ElenaGallo please

**Comment by lpasquali** [comment]
@randomorder I applied out check list (leaving the "production only steps" out like changing django secrets from the mocking ones and so on) on 3.3.x and 3.2.x geonode projects, as well build and run the compose in geonode repository, besides that I tested geopackage basic functionality for 3.3.x, results of such test needed an issue about geonode-mapstore-client https://github.com/GeoNode/geonode-mapstore-client/issues/509

**Comment by randomorder** [comment]
aside from the geonode-mapstore-client issue the task is done @lpasquali ?

**Comment by lpasquali** [comment]
@randomorder yes
