### ISSUE TITLE
CSW must return only Layers by default and other resource types only if explicitely configured

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#757]
A severe regression has been introduced with https://github.com/GeoNode/geonode/commit/c665093d949898a7a400a9e713af5a0cd8d1c159 which makes CSW return any Resource (including maps, services, etc.). The expected result, as it was before, is to only return Layers by default. If a specific context (see RNDT) requires additional types of resource a specific configuration should be set.

The `alternate_isnull` filter that we had before is not very predictable. The fix should implement the option to configure the types of resources that we want to include inside the CSW queries.

I would configure the resource class inside the settings, with only Layer by default. It could be included as a new key inside the [PYCSW dictionary](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1086), somethings like:

```
PYCSW: {
   'CONFIGURATION': {...},
   'RESOURCE_CLASSES': ['geonode.layers.models.Layer']
}
```

**Comment by giohappy** [comment]
Issue moved to [geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV #210](https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/210) via [**ZenHub**](https://www.zenhub.com/)

**Comment by etj** [comment]
CSW filtering is quite complex, and we may need something more flexible wrt only setting a filter on the resource class.

I would consider a generic dictionary
```python
PYCSW: {
   'CONFIGURATION': {...},
   'FILTER': <DICT>
}
```


so that when filtering we can pass the `dict` as a `**kwarg` to the django filter:

```python
filter_dict = settings['PYCSW`].get('FILTER', {'resource_type':'layer'}) 
return ResourceBase.objects().filter(**filter_dict)`
```

e.g. 
if we also want service's we can use django ORM notation:
```python
PYCSW: {
   'CONFIGURATION': {...},
   'FILTER': {'resource_type__in':['layer','service'] }
}```
