### ISSUE TITLE
Upgrade Geoserver 2.18 SNAPSHOT for GeoNode 3.2.x

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#791]
We need to include some improvements and fix to Geoserver 2.18.x at least from commit https://github.com/geoserver/geoserver/commit/777175da2905c2fb22668c775694ec8adda0430d

- [x] Build a new WAR from https://github.com/geoserver/geoserver/commit/777175da2905c2fb22668c775694ec8adda0430d
- [x] Replace the WAR of the current Dropbox link https://www.dropbox.com/s/xlich7pmneaupqp/geoserver-2.18.2.war. **NOTICE** that it's named **2.18.2**. Let's maintain this naming for GeoNode 3.2.x so that we don't have to change any Docker file and paver command.

**Comment by randomorder** [comment]
FYI @etj

**Comment by etj** [comment]
@giohappy I wouldn't keep a fake version name in the file name. It's really misleading.

**Comment by giohappy** [comment]
As exolained by chat this was just to make things quickly, leaving everything as it is and just bundling a new war for the snapshot.

We have started the clean up of all these things, and I want to continue it on master. If you want to do it for 3.2.x too ok, but in that case all the setup and deployment procedures must be tested again if you change the docker files, compose, etc.

**Comment by randomorder** [comment]
war file updated @giohappy
