### ISSUE TITLE
Upgrade GeoNode master to Geoserver 2.19.x

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#792]
The [work that was started for the upgrade to Geoserver 2.18.3](https://github.com/geosolutions-it/geonode/issues/790) should be done and completed to upgrade the master branch to GeoNode 2.19.1 (that will be released in a few days).

- [x] Create Build Job for GS 2.19.x for GeoNode
- [x] Create new 2.19.1 branches and port the improvements done on 2.18.3 branches of [geoserver-geonode-ext](https://github.com/GeoNode/geoserver-geonode-ext), [docker-geoserver](https://github.com/GeoNode/geoserver-docker) and [data-docker](https://github.com/GeoNode/data-docker)
- [x] Update the [docker-compose](https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L85) for GeoNode use GS 2.19.1
- [x] Update the [Dockerfile](https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/Dockerfile#L14) for geonode-project use GS 2.19.1
- [x] Test, test, test

**Remember to add the GeoPackage Plugin to GeoServer**

**Comment by randomorder** [comment]
This is quite urgent @lpasquali . Please move on with the task ASAP

**Comment by randomorder** [comment]
@giohappy between title and description there's a mix of 2.19.1 and 2.19.x. We're doing 2.19.x, right?

What should we do in terms of naming convention for artifacts in dropbox?

**Comment by lpasquali** [comment]
PR for geonode-project here: https://github.com/GeoNode/geonode-project/pull/238
PR for geonode here: https://github.com/GeoNode/geonode/pull/8127

**Comment by randomorder** [comment]
did you test on your end @lpasquali ? If that's the case pass the ball to @giohappy and @ElenaGallo please

**Comment by lpasquali** [comment]
I am don ehere on my side @randomorder

**Comment by randomorder** [comment]
closing @giohappy 
If there os anything left to do please let me know
