### ISSUE TITLE
GeoNode 3.2.1 release

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#842]
@ElenaGallo please execute the usual complete test suite.

**Comment by simboss** [comment]
@giohappy can you put more info on the instance to test?

I want to play with it myself...

**Comment by giohappy** [comment]
@simboss This version doesn't bring any relevant feature. The most important fixes are:

 - fixed a regression that made lose the permissions set at upload time - [7557](https://github.com/GeoNode/geonode/issues/7557)
 - added missing sld_version to GetLegendGrphics request for remote services - [7580](https://github.com/geonode/geonode/issues/7580)
 - fix to the thumbnail widget inside the metadatawizrd - [7638](https://github.com/GeoNode/geonode/issues/7638)
 - fix a corner case that made the legends show twice - [7587](https://github.com/GeoNode/geonode/issues/7587)
 - improved upload time with a fix to the listing of Geoserver stores - [7618](https://github.com/GeoNode/geonode/issues/7618)
 - default tile size (which is going to be fixed right away) - [7623](https://github.com/geonode/geonode/issues/7623)

You can view the full list of commits here: https://github.com/GeoNode/geonode/compare/3.2.0...3.2.x

**Comment by simboss** [comment]
Sorry, I was not clear.
Are targeting master.demo? Something else?

**Comment by giohappy** [comment]
Both instances (master and stable) are the same at the moment, by the way I would go for [http://stable.demo.geonode.org/](http://stable.demo.geonode.org/), in case we make the switch next days (I don't think it will happen though).

**Comment by giohappy** [comment]
@ElenaGallo please test again LAYERS.17.  The shapefile must have exactly the same name as the layer to be replaced.

**Comment by ElenaGallo** [comment]
@giohappy the LAYERS.17 test, by entering the same name, passes

**Comment by giohappy** [comment]
@ElenaGallo please give the failed tests a new try on [https://stable.demo.geonode.org/](https://stable.demo.geonode.org/)

**Comment by ElenaGallo** [comment]
@giohappy the following tests still fail:

https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=893953652&range=39:39

https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=260329779&range=21:21

https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=1050563143&range=10:10

https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=1595091239&range=25:25

https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=1595091239&range=36:36

**Comment by giohappy** [comment]
@ElenaGallo I'm going to set MAPSTORE.25 as passed since the test is not about vieweing the widgets inside the embedded map. It's never been supported. I've create an issue as an enhancment.

**Comment by giohappy** [comment]
MAPS.21 works fine with English language. The issue is not the setting of the thumbnail but an error inside the widget itself with the Italian translation. What do you expect it to set if it's blank @ElenaGallo? :)
I will mark the test as passed. I've opened an issue for the problem https://github.com/GeoNode/geonode/issues/7700

**Comment by giohappy** [comment]
MAPSTORE.36: widgets are not supported for layers, so this test must be removed

**Comment by giohappy** [comment]
@ElenaGallo as far as I can see the only real issue is https://github.com/geonode/geonode-mapstore-client/issues/274
All the rest is fine, right?

**Comment by ElenaGallo** [comment]
@giohappy there is still this test: https://docs.google.com/spreadsheets/d/1jNBrsRpp-uGlgDsMuThf_pHdA5M2lgaUgdHKYU-2mcw/edit#gid=1050563143&range=10:10

**Comment by giohappy** [comment]
@ElenaGallo what are you trying to do with GEOSTORY.10? Embedded code is meant to be used inside an HTML page. Did you create a page to test it? Can you share the code?

**Comment by ElenaGallo** [comment]
@giohappy yes, I create [this page](https://github.com/geosolutions-it/geonode/files/6770171/geostory.zip)

**Comment by giohappy** [comment]
@ElenaGallo it was a configuration to be fixed on the stable demo. It's working now.

**Comment by ElenaGallo** [comment]
@giohappy yes, now the test has passed

**Comment by giohappy** [comment]
@ElenaGallo please check LAYERS.39. It should be working now.
This should be the last failed test.

**Comment by ElenaGallo** [comment]
@giohappy yes, now all tests have passed
