### ISSUE TITLE
Users cannot register on new portal stable.demo.geonode.org because of invalid reCaptcha keys

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#868]
## Expected Behavior
I can register as a new user to the portal.

## Actual Behavior
The signup procedure prevents to register a new user due to reCaptcha issues
![image](https://user-images.githubusercontent.com/1278021/124121541-4e065a00-da75-11eb-9f51-f11ec290cf7c.png)

## Steps to Reproduce the Problem

  1. Go to https://stable.demo.geonode.org/account/signup/ 
  2. Try to register a new user

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

New recapthca keys must be created for this domain and placed into the `.env` file.
The docker images must be restarted (`up -d`) in order to keep the changes.

**Comment by randomorder** [comment]
Recaptcha temporarily disabled. Need a hand form Alessio to regenerate the keys

**Comment by randomorder** [comment]
stable demo updated, recaptcha enabled

Master demo to be updated (waiting for the next code update)

**Comment by randomorder** [comment]
BTW the recaptcha V2 version in the console administration page [is hidden](https://www.google.com/recaptcha/admin/create) will probably be dismissed soon. We should consider updating the code to support V3 @giohappy @afabiani

**Comment by afabiani** [comment]
@randomorder I have updated the official documentation
