### ISSUE TITLE
Developing Commands App for Management Command Jobs via API

### ISSUE THREAD

**Issue by asgharsir** [geosolutions-it/geonode#921]
Refer Epic #909: 
Issue refers to a proposal:

> "to implement a mechanism inside GeoNode to generate an HTTP API for any management command. The idea is to expose management over a common HTTP endpoint, granting of course full control of which commands we want to be exposed and under which security restrictions."

In short we are developing a feature in which our django management commands can be invoked thru admin actions, as async cronjobs. **So, the brief plan is:**
- We are creating a `geonode.commands` app, with a core function that handles permission and any validation and then call the command. We should be able to use this function from any admin actions or API call.
- Create Model and Endpoints to display and maintain job status.
- Use Celery for async execution of management commands.
- We can also add a `command` model to list all our management commands at one place, and also to be able to invoke them from one admin site.

**In this issue we are limited to following Development Steps:**
1. Create the app and add command execution functionality.
2. Test any first couple of commands.

Follow ups could be:
- Design the CronJob model, GET endpoint and more tests
- Add update status logic and its tests
- Targeted tests for specific commands
- Any new feature or QA

**Comment by asgharsir** [comment]
This issue Checklist:
- [ ] Create the App
- [ ] Add the endpoint
- [ ] Handle Permissions
- [ ] Add celery task
- [ ] Run celery for manual 'production environment' testing
- [ ] Manual Testing to ensure it is actually non blocking (async)
- [ ] Test the task
- [ ] Test the API

**Comment by giohappy** [comment]
closing in favour of a new project plan
