### ISSUE TITLE
Migrate manual testing to Cucumber Studio

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#972]
@ElenaGallo we already had a project for GeoNode on Cucumber, but I suppose the scenarios and tests are stale. 
I've renamed it to [GeoNode 3.2.x](https://studio.cucumber.io/projects/192843).

We need to:

1. align scenarios and tests to the spreadsheet that you're currently using
2. clone two new projects GeoNode 3.3.x and GeoNode master, where we will add the new features (e.g. dashboards, annotations, etc.)

@etj please create a Cucumber account (using GitHub login). Afterwards I will add you to Geosolutions organization and the GeoNode projects.

**Comment by ElenaGallo** [comment]
@giohappy the [GeoNode 3.2.x](https://studio.cucumber.io/projects/192843) test project is now update, also with the geostory.

**Comment by giohappy** [comment]
@ElenaGallo [Geonode 3.3.x](https://studio.cucumber.io/projects/291214) project is ready. Please fil it with the new tests.

**Comment by ElenaGallo** [comment]
@giohappy the new [Geonode 3.3.x](https://studio.cucumber.io/projects/291214) project is update with new tests.
