### ISSUE TITLE
The user with edit permission cannot save the changes made

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode#985]
## Expected Behavior
The user with edit permission can save changes made on map  and geostory

## Actual Behavior
The user with edit permission cannot save the changes made on map  and geostory.
Error on console:
> PATCH https://stable.demo.geonode.org/mapstore/rest/resources/3227/?full=true 403 (Forbidden)

## Steps to Reproduce the Problem

  1. Login as admin
  2. Create a map/geostory 
  3. Enable the edit permission for a user
  4. Login with the user credential
  5. Open the map/geostory 
  6. Edi it 
  7. Click on Save 

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
I could reproduce it and I see some problems.

@afabiani [this layer](https://stable.demo.geonode.org/maps/3227) has full edit permission for some users. I added myself too for a test.

1 - WFS-T is still denied for those people
2 - no rules were created for my user (giohappy)
3 - when opening the page as one of those users [the request](https://stable.demo.geonode.org/security/permissions/3227) to the security/permissions API returns 401 

What's going on?

**Comment by afabiani** [comment]
If you want to allow a user to change a map or geostory configuration, currently the only way is to make it owner of it. There's no way from the gui to allow `write` permissions on such resources

![image](https://user-images.githubusercontent.com/1278021/136800964-2b75c5b7-a8f6-419c-8422-5dd255f72849.png)

**Comment by ElenaGallo** [comment]
@giohappy @afabiani 
when as a user I have not allowed to edit (only view) the Edit Tools panel is not available and by opening the geostory it is only possible to save as a new gesotory (save as button), see gif below:
![view](https://user-images.githubusercontent.com/56537133/136804813-18722a4c-694b-4c7b-a296-69ed4240446b.gif)


When as a user I have the possibility to editthe Eidt Tools panel is available and by opening the geostory it is possible to save the gesotory (save button), see gif below:
![edit](https://user-images.githubusercontent.com/56537133/136804912-7ac686a7-8fa8-4226-b1cb-7a0b455529fa.gif)

**Comment by giohappy** [comment]
@afabiani I confirm that on geostory I get an error as a user with manage permissions:

1. geostory
2. Edit
3. Save
4. PATCH 403 Forbidden

**Comment by giohappy** [comment]
Issue created https://github.com/GeoNode/geonode/issues/8232

**Comment by giohappy** [comment]
@ElenaGallo plese test again on development. I'm going to update stable asap.
